import { useState, useMemo } from 'react';
import { Box, Typography, Button, Snackbar, Alert, CircularProgress } from '@mui/material';
import { useTranslation } from 'react-i18next';
import SaveIcon from '@mui/icons-material/Save';
import PublicIcon from '@mui/icons-material/Public';
import SearchIcon from '@mui/icons-material/Search';
import apiInstance from '../../API/apiInstance';
import { PaysModel } from '../../../models/Pays';
import { useAuth } from '../../helper/AuthProvider';
import AccessDenied from '../../helper/AccessDenied';
import '../shared/RefModern.css';
import useGetRestCountries from '../../../hooks/restCountriesHooks/useGetRestCountries';
import { RestCountry } from '../../../models/RestCountry';

const emptyForm: PaysModel = { natcod: '', natlib: '' };

function PaysModernContent() {
  const { t } = useTranslation();
  const { hasPermission } = useAuth();
  const [form, setForm] = useState<PaysModel>(emptyForm);
  const [snack, setSnack] = useState({ open: false, msg: '', sev: 'success' as any });
  const [search, setSearch] = useState('');

  const { data: countriesData, isLoading, isError, refetch } = useGetRestCountries();
  const countries: RestCountry[] = countriesData ?? [];

  const canAdd = hasPermission('Données de Base', 'add');

  const filtered = useMemo<RestCountry[]>(() => {
    if (!search) return countries;
    const q = search.toLowerCase();
    return countries.filter((c: RestCountry) =>
      c.nameFr.toLowerCase().includes(q) ||
      c.nameCommon.toLowerCase().includes(q) ||
      c.cca2.toLowerCase().includes(q) ||
      c.cca3.toLowerCase().includes(q) ||
      c.capital.toLowerCase().includes(q) ||
      c.region.toLowerCase().includes(q)
    );
  }, [countries, search]);

  if (!hasPermission('Données de Base', 'consult')) {
    return <AccessDenied message={t('donneeBase.pays.noConsultRight')} />;
  }

  const handleSubmit = async () => {
    if (!form.natlib) {
      setSnack({ open: true, msg: t('donneeBase.common.labelRequired'), sev: 'error' });
      return;
    }
    try {
      await apiInstance.post('/Pays', { natcod: '', natlib: form.natlib });
      setSnack({ open: true, msg: t('donneeBase.pays.msgAdded'), sev: 'success' });
      setForm(emptyForm);
    } catch {
      setSnack({ open: true, msg: t('donneeBase.common.saveError'), sev: 'error' });
    }
  };

  return (
    <Box className="ref-container">
      <Box className="ref-header">
        <Box>
          <Typography className="ref-header-title">{t('donneeBase.breadcrumb')}</Typography>
          <Typography className="ref-header-heading">{t('donneeBase.pays.heading')}</Typography>
          <Typography className="ref-header-sub">{t('donneeBase.pays.subtitleApi')}</Typography>
        </Box>
        <Box className="ref-header-actions">
          {canAdd && (
            <Button className="ref-save-btn" variant="contained" startIcon={<SaveIcon />} onClick={handleSubmit}>
              {t('donneeBase.common.save')}
            </Button>
          )}
        </Box>
      </Box>

      <Box className="ref-body">
        {canAdd && (
          <Box className="ref-card">
            <Box className="ref-card-header">
              <Box className="ref-card-icon"><PublicIcon fontSize="small" /></Box>
              <Typography className="ref-card-title">{t('donneeBase.pays.newTitle')}</Typography>
            </Box>
            <Box className="ref-form-grid ref-form-grid--2">
              <Box className="ref-field">
                <label>
                  {t('donneeBase.pays.codeLabel')}{' '}
                  <span style={{ color: '#8896a8', fontWeight: 400 }}>{t('donneeBase.pays.autoGenerated')}</span>
                </label>
                <input
                  type="text"
                  value=""
                  readOnly
                  placeholder={t('donneeBase.pays.autoPlaceholder')}
                  style={{ background: '#f5f7fa', color: '#8896a8' }}
                />
              </Box>
              <Box className="ref-field">
                <label>{t('donneeBase.common.label')}</label>
                <input
                  type="text"
                  value={form.natlib}
                  onChange={e => setForm(p => ({ ...p, natlib: e.target.value }))}
                  placeholder={t('donneeBase.pays.labelPlaceholder')}
                />
              </Box>
            </Box>
          </Box>
        )}

        <Box className="ref-table-section">
          <Box className="ref-table-header">
            <Typography className="ref-table-title">
              {t('donneeBase.pays.tableTitleApi', { count: filtered.length })}
            </Typography>
            <Box className="ref-table-search">
              <SearchIcon sx={{ fontSize: 16, color: '#8896a8' }} />
              <input
                type="text"
                placeholder={t('donneeBase.common.search')}
                value={search}
                onChange={e => setSearch(e.target.value)}
              />
            </Box>
          </Box>
          <Box className="ref-table-container">
            <table className="ref-table">
              <thead>
                <tr>
                  <th style={{ width: 70 }}>{t('donneeBase.pays.flag')}</th>
                  <th style={{ width: 80 }}>{t('donneeBase.common.code')}</th>
                  <th>{t('donneeBase.common.label')}</th>
                  <th>{t('donneeBase.pays.capital')}</th>
                  <th>{t('donneeBase.pays.region')}</th>
                </tr>
              </thead>
              <tbody>
                {isLoading ? (
                  <tr>
                    <td colSpan={5} className="ref-empty">
                      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', gap: 1, py: 2 }}>
                        <CircularProgress size={20} />
                        <span>{t('donneeBase.pays.loadingApi')}</span>
                      </Box>
                    </td>
                  </tr>
                ) : isError ? (
                  <tr>
                    <td colSpan={5} className="ref-empty">
                      <Box sx={{ py: 2 }}>
                        <Typography color="error" sx={{ mb: 1 }}>
                          {t('donneeBase.pays.apiError')}
                        </Typography>
                        <Button size="small" onClick={() => refetch()}>{t('donneeBase.pays.retry')}</Button>
                      </Box>
                    </td>
                  </tr>
                ) : filtered.length === 0 ? (
                  <tr><td colSpan={5} className="ref-empty">{t('donneeBase.pays.noResults')}</td></tr>
                ) : filtered.map((c: RestCountry) => (
                  <tr key={c.cca3}>
                    <td>
                      {c.flagPng && (
                        <img
                          src={c.flagPng}
                          alt={c.flagAlt || c.nameFr}
                          loading="lazy"
                          style={{ width: 36, height: 24, objectFit: 'cover', borderRadius: 3, boxShadow: '0 0 0 1px rgba(15,23,42,0.08)' }}
                        />
                      )}
                    </td>
                    <td style={{ fontWeight: 700, color: '#0f172a' }}>{c.cca3}</td>
                    <td>{c.nameFr}</td>
                    <td>{c.capital || '—'}</td>
                    <td>{c.region || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Box>
          <Box className="ref-table-footer">
            <span>{t('donneeBase.pays.footerCount', { count: filtered.length })}</span>
            <span style={{ color: '#8896a8', fontSize: 12 }}>
              {t('donneeBase.pays.sourceApi')}
            </span>
          </Box>
        </Box>
      </Box>

      <Snackbar open={snack.open} autoHideDuration={4000} onClose={() => setSnack(s => ({ ...s, open: false }))}>
        <Alert severity={snack.sev} onClose={() => setSnack(s => ({ ...s, open: false }))} sx={{ borderRadius: '10px' }}>{snack.msg}</Alert>
      </Snackbar>
    </Box>
  );
}

export default function PaysModern() {
  return <PaysModernContent />;
}
