-- =============================================================================
-- ⚠ OBSOLÈTE — NE PAS EXÉCUTER.
--
-- Ce script servait, à l'époque SQL Server, à créer manuellement la table
-- `refresh_tokens` sur une installation existante avant que l'EF migration
-- correspondante existe.
--
-- Depuis la migration SQL Server → PostgreSQL (mai 2026) :
--   - La table est créée par la migration EF "InitialCreate" :
--     ABRPOINT.Server/Migrations/20260516100635_InitialCreate.cs:3007
--   - À chaque création de tenant, ProvisioningService.RunMigrationsAsync()
--     applique InitialCreate (qui inclut refresh_tokens).
--   - Pour les tenants déjà provisionnés, BaseDataSchemaMigrator gère les
--     ajouts de colonnes ultérieurs (cf. AddRefreshTokenPurposeAndQuota.sql
--     dans ABRPOINT.Server/Migrations/ — celui-là, lui, est PG-natif).
--
-- Si vous avez encore une installation SQL Server à migrer, le contenu
-- T-SQL original reste accessible via :
--   git show <commit-pre-migration>:CREATE_REFRESH_TOKENS_TABLE.sql
-- =============================================================================
