-- ============================================================
-- RGPD Compliance Migration Script
-- Adds CreatedAt, DeletedAt, RetentionDate columns to all tables
-- Creates AuditLog table for RGPD audit trail
-- ============================================================

-- 1. Create AuditLog table (with RGPD compliance fields)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AuditLog')
BEGIN
    CREATE TABLE AuditLog (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Uticod NVARCHAR(20) NULL,
        Action NVARCHAR(100) NULL,
        TableName NVARCHAR(100) NULL,
        DateAction DATETIME NOT NULL DEFAULT GETUTCDATE(),
        CreatedAt DATETIME NULL,
        DeletedAt DATETIME NULL,
        RetentionDate DATETIME NULL
    );
END;
GO

-- 1b. If AuditLog table already exists, migrate columns
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AuditLog')
BEGIN
    -- Add Uticod column if not exists
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'Uticod')
        ALTER TABLE AuditLog ADD Uticod NVARCHAR(20) NULL;

    -- Add RGPD columns if not exists
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'CreatedAt')
        ALTER TABLE AuditLog ADD CreatedAt DATETIME NULL;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'DeletedAt')
        ALTER TABLE AuditLog ADD DeletedAt DATETIME NULL;
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'RetentionDate')
        ALTER TABLE AuditLog ADD RetentionDate DATETIME NULL;

    -- Drop old columns if they exist
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'UserId')
        ALTER TABLE AuditLog DROP COLUMN UserId;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'RecordId')
        ALTER TABLE AuditLog DROP COLUMN RecordId;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'user_id')
        ALTER TABLE AuditLog DROP COLUMN user_id;
    IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AuditLog' AND COLUMN_NAME = 'record_id')
        ALTER TABLE AuditLog DROP COLUMN record_id;
END;
GO

-- 2. Helper procedure to add column if not exists
-- Adds created_at, deleted_at, retention_date to each table

-- Absence
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Absence' AND COLUMN_NAME = 'created_at') ALTER TABLE Absence ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Absence' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Absence ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Absence' AND COLUMN_NAME = 'retention_date') ALTER TABLE Absence ADD retention_date DATETIME NULL;
GO

-- Aide
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Aide' AND COLUMN_NAME = 'created_at') ALTER TABLE Aide ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Aide' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Aide ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Aide' AND COLUMN_NAME = 'retention_date') ALTER TABLE Aide ADD retention_date DATETIME NULL;
GO

-- Allaitement
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Allaitement' AND COLUMN_NAME = 'created_at') ALTER TABLE Allaitement ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Allaitement' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Allaitement ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Allaitement' AND COLUMN_NAME = 'retention_date') ALTER TABLE Allaitement ADD retention_date DATETIME NULL;
GO

-- Anomalie
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Anomalie' AND COLUMN_NAME = 'created_at') ALTER TABLE Anomalie ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Anomalie' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Anomalie ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Anomalie' AND COLUMN_NAME = 'retention_date') ALTER TABLE Anomalie ADD retention_date DATETIME NULL;
GO

-- Article
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Article' AND COLUMN_NAME = 'created_at') ALTER TABLE Article ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Article' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Article ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Article' AND COLUMN_NAME = 'retention_date') ALTER TABLE Article ADD retention_date DATETIME NULL;
GO

-- Autoriser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Autoriser' AND COLUMN_NAME = 'created_at') ALTER TABLE Autoriser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Autoriser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Autoriser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Autoriser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Autoriser ADD retention_date DATETIME NULL;
GO

-- Avance
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Avance' AND COLUMN_NAME = 'created_at') ALTER TABLE Avance ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Avance' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Avance ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Avance' AND COLUMN_NAME = 'retention_date') ALTER TABLE Avance ADD retention_date DATETIME NULL;
GO

-- Banque
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Banque' AND COLUMN_NAME = 'created_at') ALTER TABLE Banque ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Banque' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Banque ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Banque' AND COLUMN_NAME = 'retention_date') ALTER TABLE Banque ADD retention_date DATETIME NULL;
GO

-- Billet
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Billet' AND COLUMN_NAME = 'created_at') ALTER TABLE Billet ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Billet' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Billet ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Billet' AND COLUMN_NAME = 'retention_date') ALTER TABLE Billet ADD retention_date DATETIME NULL;
GO

-- Calendsoc
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Calendsoc' AND COLUMN_NAME = 'created_at') ALTER TABLE Calendsoc ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Calendsoc' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Calendsoc ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Calendsoc' AND COLUMN_NAME = 'retention_date') ALTER TABLE Calendsoc ADD retention_date DATETIME NULL;
GO

-- Categorie
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categorie' AND COLUMN_NAME = 'created_at') ALTER TABLE Categorie ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categorie' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Categorie ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categorie' AND COLUMN_NAME = 'retention_date') ALTER TABLE Categorie ADD retention_date DATETIME NULL;
GO

-- Cloture
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cloture' AND COLUMN_NAME = 'created_at') ALTER TABLE Cloture ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cloture' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Cloture ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cloture' AND COLUMN_NAME = 'retention_date') ALTER TABLE Cloture ADD retention_date DATETIME NULL;
GO

-- Cnss
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cnss' AND COLUMN_NAME = 'created_at') ALTER TABLE Cnss ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cnss' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Cnss ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Cnss' AND COLUMN_NAME = 'retention_date') ALTER TABLE Cnss ADD retention_date DATETIME NULL;
GO

-- Coltable
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Coltable' AND COLUMN_NAME = 'created_at') ALTER TABLE Coltable ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Coltable' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Coltable ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Coltable' AND COLUMN_NAME = 'retention_date') ALTER TABLE Coltable ADD retention_date DATETIME NULL;
GO

-- Compenser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Compenser' AND COLUMN_NAME = 'created_at') ALTER TABLE Compenser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Compenser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Compenser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Compenser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Compenser ADD retention_date DATETIME NULL;
GO

-- Conge
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Conge' AND COLUMN_NAME = 'created_at') ALTER TABLE Conge ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Conge' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Conge ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Conge' AND COLUMN_NAME = 'retention_date') ALTER TABLE Conge ADD retention_date DATETIME NULL;
GO

-- Congenon
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Congenon' AND COLUMN_NAME = 'created_at') ALTER TABLE Congenon ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Congenon' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Congenon ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Congenon' AND COLUMN_NAME = 'retention_date') ALTER TABLE Congenon ADD retention_date DATETIME NULL;
GO

-- Contrat
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Contrat' AND COLUMN_NAME = 'created_at') ALTER TABLE Contrat ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Contrat' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Contrat ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Contrat' AND COLUMN_NAME = 'retention_date') ALTER TABLE Contrat ADD retention_date DATETIME NULL;
GO

-- Contrat2
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Contrat2' AND COLUMN_NAME = 'created_at') ALTER TABLE Contrat2 ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Contrat2' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Contrat2 ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Contrat2' AND COLUMN_NAME = 'retention_date') ALTER TABLE Contrat2 ADD retention_date DATETIME NULL;
GO

-- Defaut
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Defaut' AND COLUMN_NAME = 'created_at') ALTER TABLE Defaut ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Defaut' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Defaut ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Defaut' AND COLUMN_NAME = 'retention_date') ALTER TABLE Defaut ADD retention_date DATETIME NULL;
GO

-- DemandeAutorisation
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DemandeAutorisation' AND COLUMN_NAME = 'created_at') ALTER TABLE DemandeAutorisation ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DemandeAutorisation' AND COLUMN_NAME = 'deleted_at') ALTER TABLE DemandeAutorisation ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DemandeAutorisation' AND COLUMN_NAME = 'retention_date') ALTER TABLE DemandeAutorisation ADD retention_date DATETIME NULL;
GO

-- Demconge
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Demconge' AND COLUMN_NAME = 'created_at') ALTER TABLE Demconge ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Demconge' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Demconge ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Demconge' AND COLUMN_NAME = 'retention_date') ALTER TABLE Demconge ADD retention_date DATETIME NULL;
GO

-- Direction
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Direction' AND COLUMN_NAME = 'created_at') ALTER TABLE Direction ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Direction' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Direction ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Direction' AND COLUMN_NAME = 'retention_date') ALTER TABLE Direction ADD retention_date DATETIME NULL;
GO

-- Dmpoint
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Dmpoint' AND COLUMN_NAME = 'created_at') ALTER TABLE Dmpoint ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Dmpoint' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Dmpoint ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Dmpoint' AND COLUMN_NAME = 'retention_date') ALTER TABLE Dmpoint ADD retention_date DATETIME NULL;
GO

-- Dmpresence
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Dmpresence' AND COLUMN_NAME = 'created_at') ALTER TABLE Dmpresence ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Dmpresence' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Dmpresence ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Dmpresence' AND COLUMN_NAME = 'retention_date') ALTER TABLE Dmpresence ADD retention_date DATETIME NULL;
GO

-- DocumentVault
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DocumentVault' AND COLUMN_NAME = 'created_at') ALTER TABLE DocumentVault ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DocumentVault' AND COLUMN_NAME = 'deleted_at') ALTER TABLE DocumentVault ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DocumentVault' AND COLUMN_NAME = 'retention_date') ALTER TABLE DocumentVault ADD retention_date DATETIME NULL;
GO

-- Donne
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Donne' AND COLUMN_NAME = 'created_at') ALTER TABLE Donne ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Donne' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Donne ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Donne' AND COLUMN_NAME = 'retention_date') ALTER TABLE Donne ADD retention_date DATETIME NULL;
GO

-- Echelle
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Echelle' AND COLUMN_NAME = 'created_at') ALTER TABLE Echelle ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Echelle' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Echelle ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Echelle' AND COLUMN_NAME = 'retention_date') ALTER TABLE Echelle ADD retention_date DATETIME NULL;
GO

-- Empaff
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empaff' AND COLUMN_NAME = 'created_at') ALTER TABLE Empaff ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empaff' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Empaff ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empaff' AND COLUMN_NAME = 'retention_date') ALTER TABLE Empaff ADD retention_date DATETIME NULL;
GO

-- Empcat
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empcat' AND COLUMN_NAME = 'created_at') ALTER TABLE Empcat ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empcat' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Empcat ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empcat' AND COLUMN_NAME = 'retention_date') ALTER TABLE Empcat ADD retention_date DATETIME NULL;
GO

-- Empchg
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empchg' AND COLUMN_NAME = 'created_at') ALTER TABLE Empchg ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empchg' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Empchg ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empchg' AND COLUMN_NAME = 'retention_date') ALTER TABLE Empchg ADD retention_date DATETIME NULL;
GO

-- Empchoisie
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empchoisie' AND COLUMN_NAME = 'created_at') ALTER TABLE Empchoisie ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empchoisie' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Empchoisie ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empchoisie' AND COLUMN_NAME = 'retention_date') ALTER TABLE Empchoisie ADD retention_date DATETIME NULL;
GO

-- Empgrh
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empgrh' AND COLUMN_NAME = 'created_at') ALTER TABLE Empgrh ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empgrh' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Empgrh ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empgrh' AND COLUMN_NAME = 'retention_date') ALTER TABLE Empgrh ADD retention_date DATETIME NULL;
GO

-- Employe
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'employe' AND COLUMN_NAME = 'created_at') ALTER TABLE employe ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'employe' AND COLUMN_NAME = 'deleted_at') ALTER TABLE employe ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'employe' AND COLUMN_NAME = 'retention_date') ALTER TABLE employe ADD retention_date DATETIME NULL;
GO

-- Emprnd
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Emprnd' AND COLUMN_NAME = 'created_at') ALTER TABLE Emprnd ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Emprnd' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Emprnd ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Emprnd' AND COLUMN_NAME = 'retention_date') ALTER TABLE Emprnd ADD retention_date DATETIME NULL;
GO

-- Empuser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empuser' AND COLUMN_NAME = 'created_at') ALTER TABLE Empuser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empuser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Empuser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Empuser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Empuser ADD retention_date DATETIME NULL;
GO

-- Ferier
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Ferier' AND COLUMN_NAME = 'created_at') ALTER TABLE Ferier ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Ferier' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Ferier ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Ferier' AND COLUMN_NAME = 'retention_date') ALTER TABLE Ferier ADD retention_date DATETIME NULL;
GO

-- Fonction
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Fonction' AND COLUMN_NAME = 'created_at') ALTER TABLE Fonction ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Fonction' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Fonction ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Fonction' AND COLUMN_NAME = 'retention_date') ALTER TABLE Fonction ADD retention_date DATETIME NULL;
GO

-- Grille
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Grille' AND COLUMN_NAME = 'created_at') ALTER TABLE Grille ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Grille' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Grille ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Grille' AND COLUMN_NAME = 'retention_date') ALTER TABLE Grille ADD retention_date DATETIME NULL;
GO

-- Hsalaire
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Hsalaire' AND COLUMN_NAME = 'created_at') ALTER TABLE Hsalaire ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Hsalaire' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Hsalaire ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Hsalaire' AND COLUMN_NAME = 'retention_date') ALTER TABLE Hsalaire ADD retention_date DATETIME NULL;
GO

-- Lcalendsoc
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcalendsoc' AND COLUMN_NAME = 'created_at') ALTER TABLE Lcalendsoc ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcalendsoc' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lcalendsoc ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcalendsoc' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lcalendsoc ADD retention_date DATETIME NULL;
GO

-- Lcategorie
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcategorie' AND COLUMN_NAME = 'created_at') ALTER TABLE Lcategorie ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcategorie' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lcategorie ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcategorie' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lcategorie ADD retention_date DATETIME NULL;
GO

-- Lcontrat
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcontrat' AND COLUMN_NAME = 'created_at') ALTER TABLE Lcontrat ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcontrat' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lcontrat ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lcontrat' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lcontrat ADD retention_date DATETIME NULL;
GO

-- Lferier
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lferier' AND COLUMN_NAME = 'created_at') ALTER TABLE Lferier ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lferier' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lferier ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lferier' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lferier ADD retention_date DATETIME NULL;
GO

-- Lmotifpoint
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lmotifpoint' AND COLUMN_NAME = 'created_at') ALTER TABLE Lmotifpoint ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lmotifpoint' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lmotifpoint ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lmotifpoint' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lmotifpoint ADD retention_date DATETIME NULL;
GO

-- Lplanhoraire
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lplanhoraire' AND COLUMN_NAME = 'created_at') ALTER TABLE Lplanhoraire ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lplanhoraire' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lplanhoraire ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lplanhoraire' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lplanhoraire ADD retention_date DATETIME NULL;
GO

-- Lpointjour
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpointjour' AND COLUMN_NAME = 'created_at') ALTER TABLE Lpointjour ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpointjour' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lpointjour ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpointjour' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lpointjour ADD retention_date DATETIME NULL;
GO

-- Lpointmoi
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpointmoi' AND COLUMN_NAME = 'created_at') ALTER TABLE Lpointmoi ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpointmoi' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lpointmoi ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpointmoi' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lpointmoi ADD retention_date DATETIME NULL;
GO

-- Lposte
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lposte' AND COLUMN_NAME = 'created_at') ALTER TABLE Lposte ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lposte' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lposte ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lposte' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lposte ADD retention_date DATETIME NULL;
GO

-- Lpret
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpret' AND COLUMN_NAME = 'created_at') ALTER TABLE Lpret ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpret' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lpret ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lpret' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lpret ADD retention_date DATETIME NULL;
GO

-- Lregleremp
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lregleremp' AND COLUMN_NAME = 'created_at') ALTER TABLE Lregleremp ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lregleremp' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lregleremp ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lregleremp' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lregleremp ADD retention_date DATETIME NULL;
GO

-- Lsalaire
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lsalaire' AND COLUMN_NAME = 'created_at') ALTER TABLE Lsalaire ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lsalaire' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Lsalaire ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Lsalaire' AND COLUMN_NAME = 'retention_date') ALTER TABLE Lsalaire ADD retention_date DATETIME NULL;
GO

-- Mission
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Mission' AND COLUMN_NAME = 'created_at') ALTER TABLE Mission ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Mission' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Mission ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Mission' AND COLUMN_NAME = 'retention_date') ALTER TABLE Mission ADD retention_date DATETIME NULL;
GO

-- Modeopr
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Modeopr' AND COLUMN_NAME = 'created_at') ALTER TABLE Modeopr ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Modeopr' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Modeopr ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Modeopr' AND COLUMN_NAME = 'retention_date') ALTER TABLE Modeopr ADD retention_date DATETIME NULL;
GO

-- Module
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'module' AND COLUMN_NAME = 'created_at') ALTER TABLE module ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'module' AND COLUMN_NAME = 'deleted_at') ALTER TABLE module ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'module' AND COLUMN_NAME = 'retention_date') ALTER TABLE module ADD retention_date DATETIME NULL;
GO

-- Moduser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Moduser' AND COLUMN_NAME = 'created_at') ALTER TABLE Moduser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Moduser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Moduser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Moduser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Moduser ADD retention_date DATETIME NULL;
GO

-- Motifpoint
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Motifpoint' AND COLUMN_NAME = 'created_at') ALTER TABLE Motifpoint ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Motifpoint' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Motifpoint ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Motifpoint' AND COLUMN_NAME = 'retention_date') ALTER TABLE Motifpoint ADD retention_date DATETIME NULL;
GO

-- Nation
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Nation' AND COLUMN_NAME = 'created_at') ALTER TABLE Nation ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Nation' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Nation ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Nation' AND COLUMN_NAME = 'retention_date') ALTER TABLE Nation ADD retention_date DATETIME NULL;
GO

-- Opbarre
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Opbarre' AND COLUMN_NAME = 'created_at') ALTER TABLE Opbarre ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Opbarre' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Opbarre ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Opbarre' AND COLUMN_NAME = 'retention_date') ALTER TABLE Opbarre ADD retention_date DATETIME NULL;
GO

-- Operation
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Operation' AND COLUMN_NAME = 'created_at') ALTER TABLE Operation ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Operation' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Operation ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Operation' AND COLUMN_NAME = 'retention_date') ALTER TABLE Operation ADD retention_date DATETIME NULL;
GO

-- Paieuser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paieuser' AND COLUMN_NAME = 'created_at') ALTER TABLE Paieuser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paieuser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Paieuser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paieuser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Paieuser ADD retention_date DATETIME NULL;
GO

-- Paquet
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paquet' AND COLUMN_NAME = 'created_at') ALTER TABLE Paquet ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paquet' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Paquet ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paquet' AND COLUMN_NAME = 'retention_date') ALTER TABLE Paquet ADD retention_date DATETIME NULL;
GO

-- Parametre
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parametre' AND COLUMN_NAME = 'created_at') ALTER TABLE Parametre ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parametre' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Parametre ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parametre' AND COLUMN_NAME = 'retention_date') ALTER TABLE Parametre ADD retention_date DATETIME NULL;
GO

-- Paramsite
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paramsite' AND COLUMN_NAME = 'created_at') ALTER TABLE Paramsite ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paramsite' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Paramsite ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Paramsite' AND COLUMN_NAME = 'retention_date') ALTER TABLE Paramsite ADD retention_date DATETIME NULL;
GO

-- Parapprent
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parapprent' AND COLUMN_NAME = 'created_at') ALTER TABLE Parapprent ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parapprent' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Parapprent ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parapprent' AND COLUMN_NAME = 'retention_date') ALTER TABLE Parapprent ADD retention_date DATETIME NULL;
GO

-- Parposte
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parposte' AND COLUMN_NAME = 'created_at') ALTER TABLE Parposte ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parposte' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Parposte ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parposte' AND COLUMN_NAME = 'retention_date') ALTER TABLE Parposte ADD retention_date DATETIME NULL;
GO

-- Parpostsite
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parpostsite' AND COLUMN_NAME = 'created_at') ALTER TABLE Parpostsite ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parpostsite' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Parpostsite ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Parpostsite' AND COLUMN_NAME = 'retention_date') ALTER TABLE Parpostsite ADD retention_date DATETIME NULL;
GO

-- Partranche
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Partranche' AND COLUMN_NAME = 'created_at') ALTER TABLE Partranche ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Partranche' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Partranche ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Partranche' AND COLUMN_NAME = 'retention_date') ALTER TABLE Partranche ADD retention_date DATETIME NULL;
GO

-- Partranchsite
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Partranchsite' AND COLUMN_NAME = 'created_at') ALTER TABLE Partranchsite ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Partranchsite' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Partranchsite ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Partranchsite' AND COLUMN_NAME = 'retention_date') ALTER TABLE Partranchsite ADD retention_date DATETIME NULL;
GO

-- Planhoraire
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Planhoraire' AND COLUMN_NAME = 'created_at') ALTER TABLE Planhoraire ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Planhoraire' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Planhoraire ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Planhoraire' AND COLUMN_NAME = 'retention_date') ALTER TABLE Planhoraire ADD retention_date DATETIME NULL;
GO

-- Pointacce
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointacce' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointacce ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointacce' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointacce ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointacce' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointacce ADD retention_date DATETIME NULL;
GO

-- Pointdroit
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointdroit' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointdroit ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointdroit' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointdroit ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointdroit' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointdroit ADD retention_date DATETIME NULL;
GO

-- Pointeuse
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointeuse' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointeuse ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointeuse' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointeuse ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointeuse' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointeuse ADD retention_date DATETIME NULL;
GO

-- Pointheure
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointheure' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointheure ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointheure' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointheure ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointheure' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointheure ADD retention_date DATETIME NULL;
GO

-- Pointmoisj
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointmoisj' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointmoisj ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointmoisj' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointmoisj ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointmoisj' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointmoisj ADD retention_date DATETIME NULL;
GO

-- Pointsemainej
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointsemainej' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointsemainej ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointsemanej' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointsemanej ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointsemanej' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointsemanej ADD retention_date DATETIME NULL;
GO

-- Pointuser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointuser' AND COLUMN_NAME = 'created_at') ALTER TABLE Pointuser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointuser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pointuser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pointuser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pointuser ADD retention_date DATETIME NULL;
GO

-- Poste
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Poste' AND COLUMN_NAME = 'created_at') ALTER TABLE Poste ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Poste' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Poste ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Poste' AND COLUMN_NAME = 'retention_date') ALTER TABLE Poste ADD retention_date DATETIME NULL;
GO

-- Postemploye
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Postemploye' AND COLUMN_NAME = 'created_at') ALTER TABLE Postemploye ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Postemploye' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Postemploye ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Postemploye' AND COLUMN_NAME = 'retention_date') ALTER TABLE Postemploye ADD retention_date DATETIME NULL;
GO

-- Postesite
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Postesite' AND COLUMN_NAME = 'created_at') ALTER TABLE Postesite ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Postesite' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Postesite ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Postesite' AND COLUMN_NAME = 'retention_date') ALTER TABLE Postesite ADD retention_date DATETIME NULL;
GO

-- Presence
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Presence' AND COLUMN_NAME = 'created_at') ALTER TABLE Presence ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Presence' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Presence ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Presence' AND COLUMN_NAME = 'retention_date') ALTER TABLE Presence ADD retention_date DATETIME NULL;
GO

-- Presencej
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Presencej' AND COLUMN_NAME = 'created_at') ALTER TABLE Presencej ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Presencej' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Presencej ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Presencej' AND COLUMN_NAME = 'retention_date') ALTER TABLE Presencej ADD retention_date DATETIME NULL;
GO

-- Pret
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pret' AND COLUMN_NAME = 'created_at') ALTER TABLE Pret ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pret' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Pret ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Pret' AND COLUMN_NAME = 'retention_date') ALTER TABLE Pret ADD retention_date DATETIME NULL;
GO

-- Probarre
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Probarre' AND COLUMN_NAME = 'created_at') ALTER TABLE Probarre ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Probarre' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Probarre ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Probarre' AND COLUMN_NAME = 'retention_date') ALTER TABLE Probarre ADD retention_date DATETIME NULL;
GO

-- Qualif
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualif' AND COLUMN_NAME = 'created_at') ALTER TABLE Qualif ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualif' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Qualif ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualif' AND COLUMN_NAME = 'retention_date') ALTER TABLE Qualif ADD retention_date DATETIME NULL;
GO

-- Qualjrl
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualjrl' AND COLUMN_NAME = 'created_at') ALTER TABLE Qualjrl ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualjrl' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Qualjrl ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualjrl' AND COLUMN_NAME = 'retention_date') ALTER TABLE Qualjrl ADD retention_date DATETIME NULL;
GO

-- Qualmen
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualmen' AND COLUMN_NAME = 'created_at') ALTER TABLE Qualmen ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualmen' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Qualmen ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Qualmen' AND COLUMN_NAME = 'retention_date') ALTER TABLE Qualmen ADD retention_date DATETIME NULL;
GO

-- Regleremp
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Regleremp' AND COLUMN_NAME = 'created_at') ALTER TABLE Regleremp ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Regleremp' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Regleremp ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Regleremp' AND COLUMN_NAME = 'retention_date') ALTER TABLE Regleremp ADD retention_date DATETIME NULL;
GO

-- Rendjour
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rendjour' AND COLUMN_NAME = 'created_at') ALTER TABLE Rendjour ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rendjour' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Rendjour ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rendjour' AND COLUMN_NAME = 'retention_date') ALTER TABLE Rendjour ADD retention_date DATETIME NULL;
GO

-- Repo
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Repo' AND COLUMN_NAME = 'created_at') ALTER TABLE Repo ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Repo' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Repo ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Repo' AND COLUMN_NAME = 'retention_date') ALTER TABLE Repo ADD retention_date DATETIME NULL;
GO

-- Rndbareme
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rndbareme' AND COLUMN_NAME = 'created_at') ALTER TABLE Rndbareme ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rndbareme' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Rndbareme ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rndbareme' AND COLUMN_NAME = 'retention_date') ALTER TABLE Rndbareme ADD retention_date DATETIME NULL;
GO

-- RolePermission
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RolePermissions' AND COLUMN_NAME = 'created_at') ALTER TABLE RolePermissions ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RolePermissions' AND COLUMN_NAME = 'deleted_at') ALTER TABLE RolePermissions ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RolePermissions' AND COLUMN_NAME = 'retention_date') ALTER TABLE RolePermissions ADD retention_date DATETIME NULL;
GO

-- RolePointdroit
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RolePointdroits' AND COLUMN_NAME = 'created_at') ALTER TABLE RolePointdroits ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RolePointdroits' AND COLUMN_NAME = 'deleted_at') ALTER TABLE RolePointdroits ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RolePointdroits' AND COLUMN_NAME = 'retention_date') ALTER TABLE RolePointdroits ADD retention_date DATETIME NULL;
GO

-- Rubrique
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rubrique' AND COLUMN_NAME = 'created_at') ALTER TABLE Rubrique ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rubrique' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Rubrique ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rubrique' AND COLUMN_NAME = 'retention_date') ALTER TABLE Rubrique ADD retention_date DATETIME NULL;
GO

-- Rubtype
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rubtype' AND COLUMN_NAME = 'created_at') ALTER TABLE Rubtype ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rubtype' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Rubtype ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Rubtype' AND COLUMN_NAME = 'retention_date') ALTER TABLE Rubtype ADD retention_date DATETIME NULL;
GO

-- Salaire
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Salaire' AND COLUMN_NAME = 'created_at') ALTER TABLE Salaire ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Salaire' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Salaire ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Salaire' AND COLUMN_NAME = 'retention_date') ALTER TABLE Salaire ADD retention_date DATETIME NULL;
GO

-- Sanction
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Sanction' AND COLUMN_NAME = 'created_at') ALTER TABLE Sanction ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Sanction' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Sanction ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Sanction' AND COLUMN_NAME = 'retention_date') ALTER TABLE Sanction ADD retention_date DATETIME NULL;
GO

-- Section
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Section' AND COLUMN_NAME = 'created_at') ALTER TABLE Section ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Section' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Section ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Section' AND COLUMN_NAME = 'retention_date') ALTER TABLE Section ADD retention_date DATETIME NULL;
GO

-- Semaine
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Semaine' AND COLUMN_NAME = 'created_at') ALTER TABLE Semaine ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Semaine' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Semaine ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Semaine' AND COLUMN_NAME = 'retention_date') ALTER TABLE Semaine ADD retention_date DATETIME NULL;
GO

-- Service
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Service' AND COLUMN_NAME = 'created_at') ALTER TABLE Service ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Service' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Service ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Service' AND COLUMN_NAME = 'retention_date') ALTER TABLE Service ADD retention_date DATETIME NULL;
GO

-- Site
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'created_at') ALTER TABLE Site ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Site ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Site' AND COLUMN_NAME = 'retention_date') ALTER TABLE Site ADD retention_date DATETIME NULL;
GO

-- Societe
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Societe' AND COLUMN_NAME = 'created_at') ALTER TABLE Societe ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Societe' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Societe ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Societe' AND COLUMN_NAME = 'retention_date') ALTER TABLE Societe ADD retention_date DATETIME NULL;
GO

-- Socsage
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Socsage' AND COLUMN_NAME = 'created_at') ALTER TABLE Socsage ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Socsage' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Socsage ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Socsage' AND COLUMN_NAME = 'retention_date') ALTER TABLE Socsage ADD retention_date DATETIME NULL;
GO

-- Socuser
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Socuser' AND COLUMN_NAME = 'created_at') ALTER TABLE Socuser ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Socuser' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Socuser ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Socuser' AND COLUMN_NAME = 'retention_date') ALTER TABLE Socuser ADD retention_date DATETIME NULL;
GO

-- Solde
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Solde' AND COLUMN_NAME = 'created_at') ALTER TABLE Solde ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Solde' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Solde ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Solde' AND COLUMN_NAME = 'retention_date') ALTER TABLE Solde ADD retention_date DATETIME NULL;
GO

-- Soldecmp
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Soldecmp' AND COLUMN_NAME = 'created_at') ALTER TABLE Soldecmp ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Soldecmp' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Soldecmp ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Soldecmp' AND COLUMN_NAME = 'retention_date') ALTER TABLE Soldecmp ADD retention_date DATETIME NULL;
GO

-- Suivemp
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Suivemp' AND COLUMN_NAME = 'created_at') ALTER TABLE Suivemp ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Suivemp' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Suivemp ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Suivemp' AND COLUMN_NAME = 'retention_date') ALTER TABLE Suivemp ADD retention_date DATETIME NULL;
GO

-- SuvCalend
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SuvCalend' AND COLUMN_NAME = 'created_at') ALTER TABLE SuvCalend ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SuvCalend' AND COLUMN_NAME = 'deleted_at') ALTER TABLE SuvCalend ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SuvCalend' AND COLUMN_NAME = 'retention_date') ALTER TABLE SuvCalend ADD retention_date DATETIME NULL;
GO

-- TAmort
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAmort' AND COLUMN_NAME = 'created_at') ALTER TABLE TAmort ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAmort' AND COLUMN_NAME = 'deleted_at') ALTER TABLE TAmort ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TAmort' AND COLUMN_NAME = 'retention_date') ALTER TABLE TAmort ADD retention_date DATETIME NULL;
GO

-- Titre
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Titre' AND COLUMN_NAME = 'created_at') ALTER TABLE Titre ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Titre' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Titre ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Titre' AND COLUMN_NAME = 'retention_date') ALTER TABLE Titre ADD retention_date DATETIME NULL;
GO

-- Tmpclp651021
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tmpclp651021' AND COLUMN_NAME = 'created_at') ALTER TABLE Tmpclp651021 ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tmpclp651021' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Tmpclp651021 ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Tmpclp651021' AND COLUMN_NAME = 'retention_date') ALTER TABLE Tmpclp651021 ADD retention_date DATETIME NULL;
GO

-- TPret
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TPret' AND COLUMN_NAME = 'created_at') ALTER TABLE TPret ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TPret' AND COLUMN_NAME = 'deleted_at') ALTER TABLE TPret ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TPret' AND COLUMN_NAME = 'retention_date') ALTER TABLE TPret ADD retention_date DATETIME NULL;
GO

-- TRemboursement
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRemboursement' AND COLUMN_NAME = 'created_at') ALTER TABLE TRemboursement ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRemboursement' AND COLUMN_NAME = 'deleted_at') ALTER TABLE TRemboursement ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TRemboursement' AND COLUMN_NAME = 'retention_date') ALTER TABLE TRemboursement ADD retention_date DATETIME NULL;
GO

-- TSal
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TSal' AND COLUMN_NAME = 'created_at') ALTER TABLE TSal ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TSal' AND COLUMN_NAME = 'deleted_at') ALTER TABLE TSal ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TSal' AND COLUMN_NAME = 'retention_date') ALTER TABLE TSal ADD retention_date DATETIME NULL;
GO

-- TTyperemb
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TTyperemb' AND COLUMN_NAME = 'created_at') ALTER TABLE TTyperemb ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TTyperemb' AND COLUMN_NAME = 'deleted_at') ALTER TABLE TTyperemb ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TTyperemb' AND COLUMN_NAME = 'retention_date') ALTER TABLE TTyperemb ADD retention_date DATETIME NULL;
GO

-- Utilisateur
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'utilisateur' AND COLUMN_NAME = 'created_at') ALTER TABLE utilisateur ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'utilisateur' AND COLUMN_NAME = 'deleted_at') ALTER TABLE utilisateur ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'utilisateur' AND COLUMN_NAME = 'retention_date') ALTER TABLE utilisateur ADD retention_date DATETIME NULL;
GO

-- Ville
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Ville' AND COLUMN_NAME = 'created_at') ALTER TABLE Ville ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Ville' AND COLUMN_NAME = 'deleted_at') ALTER TABLE Ville ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Ville' AND COLUMN_NAME = 'retention_date') ALTER TABLE Ville ADD retention_date DATETIME NULL;
GO

-- RefreshToken (refresh_tokens)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'refresh_tokens' AND COLUMN_NAME = 'deleted_at') ALTER TABLE refresh_tokens ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'refresh_tokens' AND COLUMN_NAME = 'retention_date') ALTER TABLE refresh_tokens ADD retention_date DATETIME NULL;
GO

-- Roles
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'roles' AND COLUMN_NAME = 'created_at') ALTER TABLE roles ADD created_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'roles' AND COLUMN_NAME = 'deleted_at') ALTER TABLE roles ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'roles' AND COLUMN_NAME = 'retention_date') ALTER TABLE roles ADD retention_date DATETIME NULL;
GO

-- notedefrais (already has created_at, only add deleted_at and retention_date)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'notedefrais' AND COLUMN_NAME = 'deleted_at') ALTER TABLE notedefrais ADD deleted_at DATETIME NULL;
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'notedefrais' AND COLUMN_NAME = 'retention_date') ALTER TABLE notedefrais ADD retention_date DATETIME NULL;
GO

PRINT 'RGPD migration completed successfully.';
GO

-- ============================================================
-- Encrypt salary fields: Change empsbase, empsbrut, empsnet from float to nvarchar(256)
-- ============================================================

-- employe table: empsbase, empsbrut, empsnet
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'employe' AND COLUMN_NAME = 'empsbase')
BEGIN
    -- Add temp column, copy converted values, drop old, rename temp
    ALTER TABLE employe ADD empsbase_tmp NVARCHAR(256) NULL;
    EXEC('UPDATE employe SET empsbase_tmp = CAST(empsbase AS NVARCHAR(256)) WHERE empsbase IS NOT NULL');
    ALTER TABLE employe DROP COLUMN empsbase;
    EXEC sp_rename 'employe.empsbase_tmp', 'empsbase', 'COLUMN';
END;
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'employe' AND COLUMN_NAME = 'empsbrut')
BEGIN
    ALTER TABLE employe ADD empsbrut_tmp NVARCHAR(256) NULL;
    EXEC('UPDATE employe SET empsbrut_tmp = CAST(empsbrut AS NVARCHAR(256)) WHERE empsbrut IS NOT NULL');
    ALTER TABLE employe DROP COLUMN empsbrut;
    EXEC sp_rename 'employe.empsbrut_tmp', 'empsbrut', 'COLUMN';
END;
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'employe' AND COLUMN_NAME = 'empsnet')
BEGIN
    ALTER TABLE employe ADD empsnet_tmp NVARCHAR(256) NULL;
    EXEC('UPDATE employe SET empsnet_tmp = CAST(empsnet AS NVARCHAR(256)) WHERE empsnet IS NOT NULL');
    ALTER TABLE employe DROP COLUMN empsnet;
    EXEC sp_rename 'employe.empsnet_tmp', 'empsnet', 'COLUMN';
END;
GO

PRINT 'Salary fields migration completed successfully.';
