-- ============================================================
-- OBSOLÈTE — Migration RGPD initiale (SQL Server uniquement)
-- ============================================================
--
-- Ce script ajoutait CreatedAt / DeletedAt / RetentionDate à ~100 tables
-- sous SQL Server. Il était utilisé pour rattraper les bases déjà déployées
-- AVANT l'ajout de BaseEntity au modèle EF Core.
--
-- Depuis la migration vers PostgreSQL (commit ebcea5a et suivants), les
-- colonnes RGPD font partie de la migration EF initiale régénérée pour
-- Postgres. Toute nouvelle base créée via ProvisioningService les reçoit
-- automatiquement, et le code C# BaseDataSchemaMigrator + MobileTablesInstaller
-- couvre le rattrapage in-place.
--
-- Le script T-SQL original est conservé en historique git (commit antérieur)
-- mais n'est PLUS exécuté contre Postgres — il ne fonctionnerait pas tel quel
-- (NVARCHAR / DATETIME / sys.tables / GO / IF EXISTS BEGIN... END
--  sont SQL-Server-spécifiques).
--
-- Si tu as besoin du même rattrapage RGPD contre Postgres : utilise plutôt
-- BaseDataSchemaMigrator.EnsureBaseEntityColumnsAsync (cf. Stage 2c).
