-- ─────────────────────────────────────────────────────────────────────────
-- Hotfix : applique manuellement les changements de schéma 2026-05 pour les
-- bases de tenants existantes si la migration in-place n'a pas pu s'exécuter
-- (cf. BaseDataSchemaMigrator + MobileTablesInstaller).
--
-- À EXÉCUTER SUR CHAQUE BASE DE TENANT (tenant_xxx_yyyyyyyy) via psql :
--   psql -h ... -U abrpoint -d <db> -f AddAccountLockoutAndKnownDevices.sql
--
-- Idempotent : ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS / etc.
-- Migré T-SQL → PostgreSQL.
-- ─────────────────────────────────────────────────────────────────────────

-- 1. Account lockout (utilisateur) — ADD COLUMN IF NOT EXISTS dispo depuis PG 9.6.
ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS uti_failed_logins  INTEGER   NULL;
ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS uti_lockout_until  TIMESTAMP NULL;

-- 2. Known devices (anti-suspicious-login)
CREATE TABLE IF NOT EXISTS known_devices (
    kd_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uticod        VARCHAR(20)  NOT NULL,
    ua_hash       VARCHAR(16)  NOT NULL,
    ip_prefix     VARCHAR(40)  NOT NULL,
    device_label  VARCHAR(150) NULL,
    first_seen_at TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    last_seen_at  TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_known_devices_user_ua_ip ON known_devices(uticod, ua_hash, ip_prefix);
CREATE INDEX IF NOT EXISTS ix_known_devices_uticod ON known_devices(uticod);
