-- Migration: Add Role/2FA columns to Utilisateur + Create Roles and RolePermissions tables
-- Migré T-SQL → PostgreSQL :
--   - VARCHAR garde la même sémantique
--   - DATETIME → TIMESTAMP, GETUTCDATE() → (NOW() AT TIME ZONE 'UTC')
--   - BIT → BOOLEAN (et les inserts '1'/'0' restent VARCHAR(1) car le modèle est string)
--   - IDENTITY(1,1) → GENERATED BY DEFAULT AS IDENTITY
--   - IF NOT EXISTS (SELECT ...) → ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS
--   - Postgres folde les identifiants non-quoted en lowercase : table 'utilisateur'

-- 1. Add 2FA and Role columns to Utilisateur table
ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS utirole              VARCHAR(50)  NULL DEFAULT 'standard';
ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS utitwofactorenabled  VARCHAR(1)   NULL DEFAULT '0';
ALTER TABLE utilisateur ADD COLUMN IF NOT EXISTS utitwofactorsecret   VARCHAR(255) NULL;

-- 2. Create roles table
CREATE TABLE IF NOT EXISTS roles (
    role_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name        VARCHAR(100) NOT NULL,
    role_description VARCHAR(255) NULL,
    role_color       VARCHAR(20)  NULL DEFAULT '#64748b',
    role_is_system   BOOLEAN      NULL DEFAULT FALSE,
    role_created_at  TIMESTAMP    NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);

-- Idempotent : insert seulement si la table est vide (sinon on duplique à chaque run).
INSERT INTO roles (role_name, role_description, role_color, role_is_system)
SELECT * FROM (VALUES
    ('Administrateur',        'Accès complet à toutes les fonctionnalités', '#f59e0b', TRUE),
    ('Responsable RH',        'Gestion des employés, congés et paie',       '#3b82f6', TRUE),
    ('Superviseur Pointage',  'Supervision du pointage et des présences',   '#10b981', TRUE),
    ('Manager',               'Consultation et validation',                  '#8b5cf6', TRUE),
    ('Utilisateur Standard',  'Accès limité en consultation',                '#64748b', TRUE)
) AS v(role_name, role_description, role_color, role_is_system)
WHERE NOT EXISTS (SELECT 1 FROM roles);

-- 3. Create role_permissions table
CREATE TABLE IF NOT EXISTS role_permissions (
    rp_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rp_role_id INTEGER NOT NULL,
    rp_module  VARCHAR(100) NOT NULL,
    rp_consult VARCHAR(1) NULL DEFAULT '0',
    rp_add     VARCHAR(1) NULL DEFAULT '0',
    rp_modify  VARCHAR(1) NULL DEFAULT '0',
    rp_delete  VARCHAR(1) NULL DEFAULT '0',
    FOREIGN KEY (rp_role_id) REFERENCES roles(role_id) ON DELETE CASCADE
);

-- Permissions par défaut — idempotent (seulement si vide).
INSERT INTO role_permissions (rp_role_id, rp_module, rp_consult, rp_add, rp_modify, rp_delete)
SELECT * FROM (VALUES
    -- Administrateur : full access
    (1, 'Absences et Sanctions',  '1', '1', '1', '1'),
    (1, 'Pointage et Temps',      '1', '1', '1', '1'),
    (1, 'Gestion Employés',       '1', '1', '1', '1'),
    (1, 'Contrats et Avenants',   '1', '1', '1', '1'),
    (1, 'Paie et Rémunération',   '1', '1', '1', '1'),
    -- Responsable RH
    (2, 'Absences et Sanctions',  '1', '1', '1', '1'),
    (2, 'Pointage et Temps',      '1', '0', '0', '0'),
    (2, 'Gestion Employés',       '1', '1', '1', '1'),
    (2, 'Contrats et Avenants',   '1', '1', '1', '0'),
    (2, 'Paie et Rémunération',   '1', '1', '1', '0'),
    -- Superviseur Pointage
    (3, 'Absences et Sanctions',  '1', '1', '1', '0'),
    (3, 'Pointage et Temps',      '1', '1', '1', '1'),
    (3, 'Gestion Employés',       '1', '0', '0', '0'),
    (3, 'Contrats et Avenants',   '1', '0', '0', '0'),
    (3, 'Paie et Rémunération',   '1', '0', '0', '0'),
    -- Manager
    (4, 'Absences et Sanctions',  '1', '1', '0', '0'),
    (4, 'Pointage et Temps',      '1', '0', '0', '0'),
    (4, 'Gestion Employés',       '1', '1', '0', '0'),
    (4, 'Contrats et Avenants',   '1', '0', '0', '0'),
    (4, 'Paie et Rémunération',   '1', '0', '0', '0'),
    -- Utilisateur Standard
    (5, 'Absences et Sanctions',  '1', '0', '0', '0'),
    (5, 'Pointage et Temps',      '1', '0', '0', '0'),
    (5, 'Gestion Employés',       '1', '0', '0', '0'),
    (5, 'Contrats et Avenants',   '0', '0', '0', '0'),
    (5, 'Paie et Rémunération',   '0', '0', '0', '0')
) AS v(rp_role_id, rp_module, rp_consult, rp_add, rp_modify, rp_delete)
WHERE NOT EXISTS (SELECT 1 FROM role_permissions);

-- 4. Create role_pointdroit table (role-based pointeuse access)
CREATE TABLE IF NOT EXISTS role_pointdroit (
    rpd_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rpd_role_id INTEGER NOT NULL,
    rpd_poicod  VARCHAR(10) NOT NULL,
    rpd_soccod  VARCHAR(10) NOT NULL,
    rpd_lire    VARCHAR(1) NULL DEFAULT '0',
    rpd_purger  VARCHAR(1) NULL DEFAULT '0',
    rpd_config  VARCHAR(1) NULL DEFAULT '0',
    FOREIGN KEY (rpd_role_id) REFERENCES roles(role_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_role_pointdroit_role_soccod ON role_pointdroit(rpd_role_id, rpd_soccod);
