/*
  Crée la table push_tokens (1 par appareil) pour stocker les tokens Expo Push.
  À exécuter sur chaque base tenant existante. Les nouveaux tenants l'auront
  automatiquement via le seed initial du ProvisioningService.

  Idempotent : CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS.

  Migré SQL Server → PostgreSQL :
    NVARCHAR    → VARCHAR (UTF-8 natif côté PG)
    DATETIME2   → TIMESTAMP
    BIT         → BOOLEAN
    IDENTITY    → GENERATED BY DEFAULT AS IDENTITY
    SYSUTCDATETIME() → (NOW() AT TIME ZONE 'UTC')
    [brackets]  → "double quotes" (ou pas du tout si lowercase non-réservé)
*/

CREATE TABLE IF NOT EXISTS push_tokens (
    pt_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uticod       VARCHAR(20)  NOT NULL,
    soccod       VARCHAR(15)  NULL,
    token        VARCHAR(200) NOT NULL,
    platform     VARCHAR(20)  NULL,
    device_id    VARCHAR(100) NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    last_seen_at TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Colonnes héritées de BaseEntity (EF Core ajoute le filtre global
    -- WHERE deleted_at IS NULL à toutes les entités BaseEntity).
    deleted_at   TIMESTAMP    NULL,
    retention_date TIMESTAMP  NULL,
    -- Colonnes d'audit RGPD historiques (conservées pour compat).
    created_at_audit TIMESTAMP NULL,
    updated_at_audit TIMESTAMP NULL,
    deleted_at_audit TIMESTAMP NULL
);

CREATE INDEX IF NOT EXISTS ix_push_tokens_uticod ON push_tokens(uticod);
CREATE UNIQUE INDEX IF NOT EXISTS ux_push_tokens_token ON push_tokens(token);
