-- Migré T-SQL → PostgreSQL :
--   - dbo. → omis (pas de schéma "dbo" en PG)
--   - nvarchar → VARCHAR ; float → DOUBLE PRECISION ; datetime → TIMESTAMP
--   - IDENTITY(1,1) → GENERATED BY DEFAULT AS IDENTITY
--   - GETDATE() → (NOW() AT TIME ZONE 'UTC') pour éviter les surprises de fuseau
--   - WITH (...) options index → omises (les valeurs par défaut PG suffisent)
CREATE TABLE IF NOT EXISTS notedefrais (
    id           INTEGER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soccod       VARCHAR(6)       NOT NULL,
    empcod       VARCHAR(12)      NOT NULL,
    titre        VARCHAR(100)     NOT NULL,
    categorie    VARCHAR(50)      NOT NULL,
    montant      DOUBLE PRECISION NOT NULL,
    projet       VARCHAR(100)     NULL,
    datedepense  TIMESTAMP        NOT NULL,
    justificatif VARCHAR(255)     NULL,
    etat         VARCHAR(20)      NOT NULL DEFAULT 'Pending',
    createdat    TIMESTAMP        NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
