-- Migration: Create demande_autorisation table
-- Date: 2026-04-18 (migré T-SQL → PostgreSQL : DATETIME → TIMESTAMP, IDENTITY → GENERATED, IF NOT EXISTS natif)

CREATE TABLE IF NOT EXISTS demande_autorisation (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soccod              VARCHAR(2) NOT NULL,
    empcod              VARCHAR(12) NOT NULL,
    concod              VARCHAR(10) NULL,
    condat              TIMESTAMP NULL,
    condep              TIMESTAMP NULL,
    conret              TIMESTAMP NULL,
    connbjour           DOUBLE PRECISION NULL,
    conmotif            VARCHAR(200) NULL,
    statut              VARCHAR(20) NOT NULL DEFAULT 'En attente',
    date_demande        TIMESTAMP NULL,
    traite_par          VARCHAR(12) NULL,
    date_traitement     TIMESTAMP NULL,
    commentaire         VARCHAR(500) NULL
);
