using ABRPOINT.Server.Data;
using Microsoft.EntityFrameworkCore;

namespace ABRPOINT.Server.Services;

/// <summary>
/// Installe (idempotent) les tables nécessaires aux fonctionnalités mobiles : push_tokens,
/// push_reminder_log, notifications, notification_preferences, notification_user_settings,
/// known_devices. Utilisé à la fois par le ProvisioningService (nouveaux tenants) et
/// par un endpoint admin de rattrapage pour les tenants existants.
///
/// Pas de migration EF Core : on garde des scripts SQL plats pour pouvoir rattraper les
/// tenants déjà déployés sans intervention DBA. Migré SQL Server → PostgreSQL : on remplace
/// `IF NOT EXISTS (SELECT 1 FROM sys.tables ...)` par `CREATE TABLE IF NOT EXISTS` natif et
/// `sys.columns` par `information_schema.columns`.
/// </summary>
public static class MobileTablesInstaller
{
    public sealed record InstallReport(
        bool PushTokensCreated,
        bool PushReminderLogCreated,
        bool NotificationsCreated,
        bool NotificationPreferencesCreated,
        bool ChannelColumnsAdded,
        bool UserSettingsCreated,
        bool KnownDevicesCreated);

    public static async Task<InstallReport> InstallAsync(ApplicationDbContext db, CancellationToken ct = default)
    {
        var pushTokens = await EnsurePushTokensAsync(db, ct);
        var reminderLog = await EnsurePushReminderLogAsync(db, ct);
        var notifications = await EnsureNotificationsAsync(db, ct);
        var prefs = await EnsureNotificationPreferencesAsync(db, ct);
        // Migration en place pour les tenants ayant créé la table prefs avant le split push/inapp.
        var channels = await EnsurePreferenceChannelsAsync(db, ct);
        var settings = await EnsureUserSettingsAsync(db, ct);
        var knownDevices = await EnsureKnownDevicesAsync(db, ct);
        return new InstallReport(pushTokens, reminderLog, notifications, prefs, channels, settings, knownDevices);
    }

    /// <summary>
    /// Crée la table d'empreintes d'appareils connus utilisée pour l'alerte "connexion
    /// depuis un nouvel appareil". Aucune donnée brute (UA / IP complète) n'est stockée :
    /// seul un hash tronqué + un préfixe de réseau. Idempotent.
    /// </summary>
    private static async Task<bool> EnsureKnownDevicesAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var existed = await TableExistsAsync(db, "known_devices", ct);
        if (existed) return false;
        await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE known_devices (
    kd_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uticod        VARCHAR(20)  NOT NULL,
    ua_hash       VARCHAR(16)  NOT NULL,
    ip_prefix     VARCHAR(40)  NOT NULL,
    device_label  VARCHAR(150) NULL,
    first_seen_at TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    last_seen_at  TIMESTAMP    NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
CREATE UNIQUE INDEX ux_known_devices_user_ua_ip ON known_devices(uticod, ua_hash, ip_prefix);
CREATE INDEX ix_known_devices_uticod ON known_devices(uticod);
", ct);
        return true;
    }

    private static async Task<bool> EnsureUserSettingsAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var existed = await TableExistsAsync(db, "notification_user_settings", ct);
        if (existed)
        {
            // Migration in-place : ajoute quiet_mode si absent (introduit après le 1er déploiement).
            var hasMode = await ColumnExistsAsync(db, "notification_user_settings", "quiet_mode", ct);
            if (!hasMode)
            {
                await db.Database.ExecuteSqlRawAsync(
                    "ALTER TABLE notification_user_settings ADD COLUMN quiet_mode VARCHAR(20) NOT NULL DEFAULT 'manual';", ct);
            }
            // BaseEntity attend created_at / deleted_at / retention_date sur toutes les entités —
            // ces colonnes étaient absentes du CREATE initial. On les ajoute en place pour les
            // bases déjà créées sans les casser.
            await EnsureBaseEntityColumnsAsync(db, "notification_user_settings", ct);
            return false;
        }
        await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE notification_user_settings (
    uticod        VARCHAR(20) NOT NULL PRIMARY KEY,
    quiet_enabled BOOLEAN     NOT NULL DEFAULT FALSE,
    quiet_mode    VARCHAR(20) NOT NULL DEFAULT 'manual',
    quiet_start   VARCHAR(5)  NOT NULL DEFAULT '22:00',
    quiet_end     VARCHAR(5)  NOT NULL DEFAULT '07:00',
    updated_at    TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    -- Colonnes héritées de BaseEntity. EF Core les attend sur chaque entité
    -- (filtre global WHERE deleted_at IS NULL).
    created_at    TIMESTAMP   NULL,
    deleted_at    TIMESTAMP   NULL,
    retention_date TIMESTAMP  NULL,
    -- Colonnes d'audit RGPD historiques (conservées pour compat).
    created_at_audit TIMESTAMP NULL,
    updated_at_audit TIMESTAMP NULL,
    deleted_at_audit TIMESTAMP NULL
);
", ct);
        return true;
    }

    /// <summary>
    /// Ajoute idempotemment les 3 colonnes BaseEntity (created_at, deleted_at, retention_date)
    /// si elles ne sont pas présentes. Utilisé pour rattraper les tables créées avant que
    /// BaseEntity ne soit appliqué partout. PostgreSQL supporte ADD COLUMN IF NOT EXISTS
    /// nativement depuis 9.6, donc un seul ALTER suffit (vs trois lookups sys.columns sous
    /// SQL Server).
    /// </summary>
    private static async Task EnsureBaseEntityColumnsAsync(ApplicationDbContext db, string table, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync($@"
ALTER TABLE {table} ADD COLUMN IF NOT EXISTS created_at     TIMESTAMP NULL;
ALTER TABLE {table} ADD COLUMN IF NOT EXISTS deleted_at     TIMESTAMP NULL;
ALTER TABLE {table} ADD COLUMN IF NOT EXISTS retention_date TIMESTAMP NULL;
", ct);
    }

    /// <summary>
    /// Ajoute idempotemment les colonnes push_enabled / inapp_enabled à notification_preferences
    /// si elles n'existent pas (migration en place pour les tenants déjà créés avec la 1ère version).
    /// </summary>
    private static async Task<bool> EnsurePreferenceChannelsAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var pushExists = await ColumnExistsAsync(db, "notification_preferences", "push_enabled", ct);
        var inappExists = await ColumnExistsAsync(db, "notification_preferences", "inapp_enabled", ct);
        if (pushExists && inappExists) return false;

        if (!pushExists)
        {
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE notification_preferences ADD COLUMN push_enabled BOOLEAN NOT NULL DEFAULT TRUE;", ct);
        }
        if (!inappExists)
        {
            await db.Database.ExecuteSqlRawAsync(
                "ALTER TABLE notification_preferences ADD COLUMN inapp_enabled BOOLEAN NOT NULL DEFAULT TRUE;", ct);
        }
        // Aligne les nouvelles colonnes avec l'ancien master switch : si enabled=0 → push=0 et inapp=0.
        await db.Database.ExecuteSqlRawAsync(
            "UPDATE notification_preferences SET push_enabled = FALSE, inapp_enabled = FALSE WHERE enabled = FALSE;", ct);
        return true;
    }

    /// <summary>
    /// Lookup colonne via information_schema (équivalent portable de sys.columns).
    /// Note : table_name lowercase obligatoire — PostgreSQL folde les identifiants
    /// non-quoted, ce qui veut dire que CREATE TABLE Foo stocke 'foo' dans le catalog.
    /// </summary>
    private static async Task<bool> ColumnExistsAsync(ApplicationDbContext db, string tableName, string columnName, CancellationToken ct)
    {
        var conn = db.Database.GetDbConnection();
        if (conn.State != System.Data.ConnectionState.Open) await conn.OpenAsync(ct);
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = @"SELECT COUNT(1) FROM information_schema.columns
                            WHERE table_schema = current_schema()
                              AND table_name   = @t
                              AND column_name  = @c";
        var pT = cmd.CreateParameter(); pT.ParameterName = "@t"; pT.Value = tableName; cmd.Parameters.Add(pT);
        var pC = cmd.CreateParameter(); pC.ParameterName = "@c"; pC.Value = columnName; cmd.Parameters.Add(pC);
        var result = await cmd.ExecuteScalarAsync(ct);
        return Convert.ToInt32(result) > 0;
    }

    private static async Task<bool> EnsureNotificationPreferencesAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var existed = await TableExistsAsync(db, "notification_preferences", ct);
        if (existed)
        {
            // Rattrapage pour les tenants déployés avant l'ajout des colonnes BaseEntity.
            await EnsureBaseEntityColumnsAsync(db, "notification_preferences", ct);
            return false;
        }
        await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE notification_preferences (
    np_id         INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uticod        VARCHAR(20) NOT NULL,
    category      VARCHAR(50) NOT NULL,
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    push_enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
    inapp_enabled BOOLEAN     NOT NULL DEFAULT TRUE,
    updated_at    TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    -- Colonnes héritées de BaseEntity (EF Core les attend sur chaque entité).
    created_at    TIMESTAMP   NULL,
    deleted_at    TIMESTAMP   NULL,
    retention_date TIMESTAMP  NULL,
    -- Colonnes d'audit RGPD historiques.
    created_at_audit TIMESTAMP NULL,
    updated_at_audit TIMESTAMP NULL,
    deleted_at_audit TIMESTAMP NULL
);
CREATE UNIQUE INDEX ux_np_user_category ON notification_preferences(uticod, category);
", ct);
        return true;
    }

    private static async Task<bool> EnsureNotificationsAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var existed = await TableExistsAsync(db, "notifications", ct);
        if (existed) return false;
        await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE notifications (
    notif_id   INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uticod     VARCHAR(20)   NOT NULL,
    soccod     VARCHAR(15)   NULL,
    title      VARCHAR(150)  NOT NULL,
    body       VARCHAR(500)  NOT NULL,
    category   VARCHAR(50)   NULL,
    data_json  TEXT          NULL,
    read_at    TIMESTAMP     NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    deleted_at TIMESTAMP     NULL,
    created_at_audit TIMESTAMP NULL,
    updated_at_audit TIMESTAMP NULL,
    deleted_at_audit TIMESTAMP NULL
);
CREATE INDEX ix_notifications_uticod_created ON notifications(uticod, created_at DESC);
-- Index partiel : équivalent Postgres du filtered index SQL Server WHERE [read_at] IS NULL.
CREATE INDEX ix_notifications_uticod_read ON notifications(uticod) WHERE read_at IS NULL;
", ct);
        return true;
    }

    private static async Task<bool> EnsurePushTokensAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var existed = await TableExistsAsync(db, "push_tokens", ct);
        if (existed)
        {
            // Tenants déployés avant l'application de BaseEntity à PushToken : la table
            // n'a ni deleted_at ni retention_date, et EF Core ajoute toujours le filtre
            // global "WHERE deleted_at IS NULL" → SQL renvoie une erreur de colonne
            // manquante. On rattrape en place.
            await EnsureBaseEntityColumnsAsync(db, "push_tokens", ct);
            return false;
        }
        await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE push_tokens (
    pt_id        INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uticod       VARCHAR(20)   NOT NULL,
    soccod       VARCHAR(15)   NULL,
    token        VARCHAR(200)  NOT NULL,
    platform     VARCHAR(20)   NULL,
    device_id    VARCHAR(100)  NULL,
    created_at   TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    last_seen_at TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    active       BOOLEAN       NOT NULL DEFAULT TRUE,
    -- BaseEntity (cf. push_reminder_log).
    deleted_at   TIMESTAMP     NULL,
    retention_date TIMESTAMP   NULL,
    created_at_audit TIMESTAMP NULL,
    updated_at_audit TIMESTAMP NULL,
    deleted_at_audit TIMESTAMP NULL
);
CREATE INDEX ix_push_tokens_uticod ON push_tokens(uticod);
CREATE UNIQUE INDEX ux_push_tokens_token ON push_tokens(token);
", ct);
        return true;
    }

    private static async Task<bool> EnsurePushReminderLogAsync(ApplicationDbContext db, CancellationToken ct)
    {
        var existed = await TableExistsAsync(db, "push_reminder_log", ct);
        if (existed)
        {
            // Même rattrapage que push_tokens : PushReminderLog hérite aussi de BaseEntity.
            await EnsureBaseEntityColumnsAsync(db, "push_reminder_log", ct);
            return false;
        }
        await db.Database.ExecuteSqlRawAsync(@"
CREATE TABLE push_reminder_log (
    prl_id   INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empcod   VARCHAR(20) NOT NULL,
    soccod   VARCHAR(15) NULL,
    type     VARCHAR(10) NOT NULL,
    for_date TIMESTAMP   NOT NULL,
    sent_at  TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    -- Colonnes BaseEntity, cf. commentaire dans push_tokens.
    created_at TIMESTAMP   NULL,
    deleted_at TIMESTAMP   NULL,
    retention_date TIMESTAMP NULL,
    created_at_audit TIMESTAMP NULL,
    updated_at_audit TIMESTAMP NULL,
    deleted_at_audit TIMESTAMP NULL
);
CREATE UNIQUE INDEX ux_push_reminder_log ON push_reminder_log(empcod, for_date, type);
", ct);
        return true;
    }

    /// <summary>
    /// Lookup table via information_schema (équivalent portable de sys.tables).
    /// Le `table_schema = current_schema()` cible le schéma courant (public par défaut
    /// en Postgres) et évite de matcher d'autres schémas qui auraient une table
    /// homonyme (pg_catalog, information_schema, etc.).
    /// </summary>
    private static async Task<bool> TableExistsAsync(ApplicationDbContext db, string tableName, CancellationToken ct)
    {
        var conn = db.Database.GetDbConnection();
        if (conn.State != System.Data.ConnectionState.Open) await conn.OpenAsync(ct);
        await using var cmd = conn.CreateCommand();
        cmd.CommandText = @"SELECT COUNT(1) FROM information_schema.tables
                            WHERE table_schema = current_schema()
                              AND table_name   = @name";
        var p = cmd.CreateParameter();
        p.ParameterName = "@name";
        p.Value = tableName;
        cmd.Parameters.Add(p);
        var result = await cmd.ExecuteScalarAsync(ct);
        return Convert.ToInt32(result) > 0;
    }
}
