// ──────────────────────────────────────────────────────────────────────────────
// Liste statique des pays (source : jeu de donnees mledoze/countries, domaine public).
// Embarquee dans le bundle pour NE PAS dependre a l'execution de restcountries.com
// (API v3.1 depreciee -> preflight CORS en echec -> liste de pays vide en prod).
// Les drapeaux sont servis par flagcdn.com via <img> (pas de contrainte CORS pour le
// rendu d'image). cf. RestCountriesService/GetRestCountries.ts.
// Fichier genere automatiquement -- 250 pays, tries par nom francais.
// ──────────────────────────────────────────────────────────────────────────────

export interface CountryDatum {
  cca2: string;
  cca3: string;
  nameFr: string;
  nameCommon: string;
}

export const COUNTRIES_DATA: CountryDatum[] = [
  { cca2: 'AF', cca3: 'AFG', nameFr: 'Afghanistan', nameCommon: 'Afghanistan' },
  { cca2: 'ZA', cca3: 'ZAF', nameFr: 'Afrique du Sud', nameCommon: 'South Africa' },
  { cca2: 'AX', cca3: 'ALA', nameFr: 'Ahvenanmaa', nameCommon: 'Åland Islands' },
  { cca2: 'AL', cca3: 'ALB', nameFr: 'Albanie', nameCommon: 'Albania' },
  { cca2: 'DZ', cca3: 'DZA', nameFr: 'Algérie', nameCommon: 'Algeria' },
  { cca2: 'DE', cca3: 'DEU', nameFr: 'Allemagne', nameCommon: 'Germany' },
  { cca2: 'AD', cca3: 'AND', nameFr: 'Andorre', nameCommon: 'Andorra' },
  { cca2: 'AO', cca3: 'AGO', nameFr: 'Angola', nameCommon: 'Angola' },
  { cca2: 'AI', cca3: 'AIA', nameFr: 'Anguilla', nameCommon: 'Anguilla' },
  { cca2: 'AQ', cca3: 'ATA', nameFr: 'Antarctique', nameCommon: 'Antarctica' },
  { cca2: 'AG', cca3: 'ATG', nameFr: 'Antigua-et-Barbuda', nameCommon: 'Antigua and Barbuda' },
  { cca2: 'SA', cca3: 'SAU', nameFr: 'Arabie Saoudite', nameCommon: 'Saudi Arabia' },
  { cca2: 'AR', cca3: 'ARG', nameFr: 'Argentine', nameCommon: 'Argentina' },
  { cca2: 'AM', cca3: 'ARM', nameFr: 'Arménie', nameCommon: 'Armenia' },
  { cca2: 'AW', cca3: 'ABW', nameFr: 'Aruba', nameCommon: 'Aruba' },
  { cca2: 'AU', cca3: 'AUS', nameFr: 'Australie', nameCommon: 'Australia' },
  { cca2: 'AT', cca3: 'AUT', nameFr: 'Autriche', nameCommon: 'Austria' },
  { cca2: 'AZ', cca3: 'AZE', nameFr: 'Azerbaïdjan', nameCommon: 'Azerbaijan' },
  { cca2: 'BS', cca3: 'BHS', nameFr: 'Bahamas', nameCommon: 'Bahamas' },
  { cca2: 'BH', cca3: 'BHR', nameFr: 'Bahreïn', nameCommon: 'Bahrain' },
  { cca2: 'BD', cca3: 'BGD', nameFr: 'Bangladesh', nameCommon: 'Bangladesh' },
  { cca2: 'BB', cca3: 'BRB', nameFr: 'Barbade', nameCommon: 'Barbados' },
  { cca2: 'BE', cca3: 'BEL', nameFr: 'Belgique', nameCommon: 'Belgium' },
  { cca2: 'BZ', cca3: 'BLZ', nameFr: 'Belize', nameCommon: 'Belize' },
  { cca2: 'BJ', cca3: 'BEN', nameFr: 'Bénin', nameCommon: 'Benin' },
  { cca2: 'BM', cca3: 'BMU', nameFr: 'Bermudes', nameCommon: 'Bermuda' },
  { cca2: 'BT', cca3: 'BTN', nameFr: 'Bhoutan', nameCommon: 'Bhutan' },
  { cca2: 'BY', cca3: 'BLR', nameFr: 'Biélorussie', nameCommon: 'Belarus' },
  { cca2: 'MM', cca3: 'MMR', nameFr: 'Birmanie', nameCommon: 'Myanmar' },
  { cca2: 'BO', cca3: 'BOL', nameFr: 'Bolivie', nameCommon: 'Bolivia' },
  { cca2: 'BA', cca3: 'BIH', nameFr: 'Bosnie-Herzégovine', nameCommon: 'Bosnia and Herzegovina' },
  { cca2: 'BW', cca3: 'BWA', nameFr: 'Botswana', nameCommon: 'Botswana' },
  { cca2: 'BR', cca3: 'BRA', nameFr: 'Brésil', nameCommon: 'Brazil' },
  { cca2: 'BN', cca3: 'BRN', nameFr: 'Brunei', nameCommon: 'Brunei' },
  { cca2: 'BG', cca3: 'BGR', nameFr: 'Bulgarie', nameCommon: 'Bulgaria' },
  { cca2: 'BF', cca3: 'BFA', nameFr: 'Burkina Faso', nameCommon: 'Burkina Faso' },
  { cca2: 'BI', cca3: 'BDI', nameFr: 'Burundi', nameCommon: 'Burundi' },
  { cca2: 'KH', cca3: 'KHM', nameFr: 'Cambodge', nameCommon: 'Cambodia' },
  { cca2: 'CM', cca3: 'CMR', nameFr: 'Cameroun', nameCommon: 'Cameroon' },
  { cca2: 'CA', cca3: 'CAN', nameFr: 'Canada', nameCommon: 'Canada' },
  { cca2: 'CL', cca3: 'CHL', nameFr: 'Chili', nameCommon: 'Chile' },
  { cca2: 'CN', cca3: 'CHN', nameFr: 'Chine', nameCommon: 'China' },
  { cca2: 'CY', cca3: 'CYP', nameFr: 'Chypre', nameCommon: 'Cyprus' },
  { cca2: 'VA', cca3: 'VAT', nameFr: 'Cité du Vatican', nameCommon: 'Vatican City' },
  { cca2: 'CO', cca3: 'COL', nameFr: 'Colombie', nameCommon: 'Colombia' },
  { cca2: 'KM', cca3: 'COM', nameFr: 'Comores', nameCommon: 'Comoros' },
  { cca2: 'CG', cca3: 'COG', nameFr: 'Congo', nameCommon: 'Congo' },
  { cca2: 'CD', cca3: 'COD', nameFr: 'Congo (Rép. dém.)', nameCommon: 'DR Congo' },
  { cca2: 'KP', cca3: 'PRK', nameFr: 'Corée du Nord', nameCommon: 'North Korea' },
  { cca2: 'KR', cca3: 'KOR', nameFr: 'Corée du Sud', nameCommon: 'South Korea' },
  { cca2: 'CR', cca3: 'CRI', nameFr: 'Costa Rica', nameCommon: 'Costa Rica' },
  { cca2: 'CI', cca3: 'CIV', nameFr: 'Côte d\'Ivoire', nameCommon: 'Ivory Coast' },
  { cca2: 'HR', cca3: 'HRV', nameFr: 'Croatie', nameCommon: 'Croatia' },
  { cca2: 'CU', cca3: 'CUB', nameFr: 'Cuba', nameCommon: 'Cuba' },
  { cca2: 'CW', cca3: 'CUW', nameFr: 'Curaçao', nameCommon: 'Curaçao' },
  { cca2: 'DK', cca3: 'DNK', nameFr: 'Danemark', nameCommon: 'Denmark' },
  { cca2: 'DJ', cca3: 'DJI', nameFr: 'Djibouti', nameCommon: 'Djibouti' },
  { cca2: 'DM', cca3: 'DMA', nameFr: 'Dominique', nameCommon: 'Dominica' },
  { cca2: 'EG', cca3: 'EGY', nameFr: 'Égypte', nameCommon: 'Egypt' },
  { cca2: 'AE', cca3: 'ARE', nameFr: 'Émirats arabes unis', nameCommon: 'United Arab Emirates' },
  { cca2: 'EC', cca3: 'ECU', nameFr: 'Équateur', nameCommon: 'Ecuador' },
  { cca2: 'ER', cca3: 'ERI', nameFr: 'Érythrée', nameCommon: 'Eritrea' },
  { cca2: 'ES', cca3: 'ESP', nameFr: 'Espagne', nameCommon: 'Spain' },
  { cca2: 'EE', cca3: 'EST', nameFr: 'Estonie', nameCommon: 'Estonia' },
  { cca2: 'SZ', cca3: 'SWZ', nameFr: 'Eswatini', nameCommon: 'Eswatini' },
  { cca2: 'US', cca3: 'USA', nameFr: 'États-Unis', nameCommon: 'United States' },
  { cca2: 'ET', cca3: 'ETH', nameFr: 'Éthiopie', nameCommon: 'Ethiopia' },
  { cca2: 'FJ', cca3: 'FJI', nameFr: 'Fidji', nameCommon: 'Fiji' },
  { cca2: 'FI', cca3: 'FIN', nameFr: 'Finlande', nameCommon: 'Finland' },
  { cca2: 'FR', cca3: 'FRA', nameFr: 'France', nameCommon: 'France' },
  { cca2: 'GA', cca3: 'GAB', nameFr: 'Gabon', nameCommon: 'Gabon' },
  { cca2: 'GM', cca3: 'GMB', nameFr: 'Gambie', nameCommon: 'Gambia' },
  { cca2: 'GE', cca3: 'GEO', nameFr: 'Géorgie', nameCommon: 'Georgia' },
  { cca2: 'GS', cca3: 'SGS', nameFr: 'Géorgie du Sud-et-les Îles Sandwich du Sud', nameCommon: 'South Georgia' },
  { cca2: 'GH', cca3: 'GHA', nameFr: 'Ghana', nameCommon: 'Ghana' },
  { cca2: 'GI', cca3: 'GIB', nameFr: 'Gibraltar', nameCommon: 'Gibraltar' },
  { cca2: 'GR', cca3: 'GRC', nameFr: 'Grèce', nameCommon: 'Greece' },
  { cca2: 'GD', cca3: 'GRD', nameFr: 'Grenade', nameCommon: 'Grenada' },
  { cca2: 'GL', cca3: 'GRL', nameFr: 'Groenland', nameCommon: 'Greenland' },
  { cca2: 'GP', cca3: 'GLP', nameFr: 'Guadeloupe', nameCommon: 'Guadeloupe' },
  { cca2: 'GU', cca3: 'GUM', nameFr: 'Guam', nameCommon: 'Guam' },
  { cca2: 'GT', cca3: 'GTM', nameFr: 'Guatemala', nameCommon: 'Guatemala' },
  { cca2: 'GG', cca3: 'GGY', nameFr: 'Guernesey', nameCommon: 'Guernsey' },
  { cca2: 'GN', cca3: 'GIN', nameFr: 'Guinée', nameCommon: 'Guinea' },
  { cca2: 'GQ', cca3: 'GNQ', nameFr: 'Guinée équatoriale', nameCommon: 'Equatorial Guinea' },
  { cca2: 'GW', cca3: 'GNB', nameFr: 'Guinée-Bissau', nameCommon: 'Guinea-Bissau' },
  { cca2: 'GY', cca3: 'GUY', nameFr: 'Guyana', nameCommon: 'Guyana' },
  { cca2: 'GF', cca3: 'GUF', nameFr: 'Guyane', nameCommon: 'French Guiana' },
  { cca2: 'HT', cca3: 'HTI', nameFr: 'Haïti', nameCommon: 'Haiti' },
  { cca2: 'HN', cca3: 'HND', nameFr: 'Honduras', nameCommon: 'Honduras' },
  { cca2: 'HK', cca3: 'HKG', nameFr: 'Hong Kong', nameCommon: 'Hong Kong' },
  { cca2: 'HU', cca3: 'HUN', nameFr: 'Hongrie', nameCommon: 'Hungary' },
  { cca2: 'BV', cca3: 'BVT', nameFr: 'Île Bouvet', nameCommon: 'Bouvet Island' },
  { cca2: 'CX', cca3: 'CXR', nameFr: 'Île Christmas', nameCommon: 'Christmas Island' },
  { cca2: 'IM', cca3: 'IMN', nameFr: 'Île de Man', nameCommon: 'Isle of Man' },
  { cca2: 'MU', cca3: 'MUS', nameFr: 'Île Maurice', nameCommon: 'Mauritius' },
  { cca2: 'NF', cca3: 'NFK', nameFr: 'Île Norfolk', nameCommon: 'Norfolk Island' },
  { cca2: 'KY', cca3: 'CYM', nameFr: 'Îles Caïmans', nameCommon: 'Cayman Islands' },
  { cca2: 'CC', cca3: 'CCK', nameFr: 'Îles Cocos', nameCommon: 'Cocos (Keeling) Islands' },
  { cca2: 'CK', cca3: 'COK', nameFr: 'Îles Cook', nameCommon: 'Cook Islands' },
  { cca2: 'CV', cca3: 'CPV', nameFr: 'Îles du Cap-Vert', nameCommon: 'Cape Verde' },
  { cca2: 'FO', cca3: 'FRO', nameFr: 'Îles Féroé', nameCommon: 'Faroe Islands' },
  { cca2: 'HM', cca3: 'HMD', nameFr: 'Îles Heard-et-MacDonald', nameCommon: 'Heard Island and McDonald Islands' },
  { cca2: 'FK', cca3: 'FLK', nameFr: 'Îles Malouines', nameCommon: 'Falkland Islands' },
  { cca2: 'MP', cca3: 'MNP', nameFr: 'Îles Mariannes du Nord', nameCommon: 'Northern Mariana Islands' },
  { cca2: 'MH', cca3: 'MHL', nameFr: 'Îles Marshall', nameCommon: 'Marshall Islands' },
  { cca2: 'UM', cca3: 'UMI', nameFr: 'Îles mineures éloignées des États-Unis', nameCommon: 'United States Minor Outlying Islands' },
  { cca2: 'PN', cca3: 'PCN', nameFr: 'Îles Pitcairn', nameCommon: 'Pitcairn Islands' },
  { cca2: 'SB', cca3: 'SLB', nameFr: 'Îles Salomon', nameCommon: 'Solomon Islands' },
  { cca2: 'TC', cca3: 'TCA', nameFr: 'Îles Turques-et-Caïques', nameCommon: 'Turks and Caicos Islands' },
  { cca2: 'VG', cca3: 'VGB', nameFr: 'Îles Vierges britanniques', nameCommon: 'British Virgin Islands' },
  { cca2: 'VI', cca3: 'VIR', nameFr: 'Îles Vierges des États-Unis', nameCommon: 'United States Virgin Islands' },
  { cca2: 'IN', cca3: 'IND', nameFr: 'Inde', nameCommon: 'India' },
  { cca2: 'ID', cca3: 'IDN', nameFr: 'Indonésie', nameCommon: 'Indonesia' },
  { cca2: 'IQ', cca3: 'IRQ', nameFr: 'Irak', nameCommon: 'Iraq' },
  { cca2: 'IR', cca3: 'IRN', nameFr: 'Iran', nameCommon: 'Iran' },
  { cca2: 'IE', cca3: 'IRL', nameFr: 'Irlande', nameCommon: 'Ireland' },
  { cca2: 'IS', cca3: 'ISL', nameFr: 'Islande', nameCommon: 'Iceland' },
  { cca2: 'IL', cca3: 'ISR', nameFr: 'Israël', nameCommon: 'Israel' },
  { cca2: 'IT', cca3: 'ITA', nameFr: 'Italie', nameCommon: 'Italy' },
  { cca2: 'JM', cca3: 'JAM', nameFr: 'Jamaïque', nameCommon: 'Jamaica' },
  { cca2: 'JP', cca3: 'JPN', nameFr: 'Japon', nameCommon: 'Japan' },
  { cca2: 'JE', cca3: 'JEY', nameFr: 'Jersey', nameCommon: 'Jersey' },
  { cca2: 'JO', cca3: 'JOR', nameFr: 'Jordanie', nameCommon: 'Jordan' },
  { cca2: 'KZ', cca3: 'KAZ', nameFr: 'Kazakhstan', nameCommon: 'Kazakhstan' },
  { cca2: 'KE', cca3: 'KEN', nameFr: 'Kenya', nameCommon: 'Kenya' },
  { cca2: 'KG', cca3: 'KGZ', nameFr: 'Kirghizistan', nameCommon: 'Kyrgyzstan' },
  { cca2: 'KI', cca3: 'KIR', nameFr: 'Kiribati', nameCommon: 'Kiribati' },
  { cca2: 'XK', cca3: 'UNK', nameFr: 'Kosovo', nameCommon: 'Kosovo' },
  { cca2: 'KW', cca3: 'KWT', nameFr: 'Koweït', nameCommon: 'Kuwait' },
  { cca2: 'LA', cca3: 'LAO', nameFr: 'Laos', nameCommon: 'Laos' },
  { cca2: 'LS', cca3: 'LSO', nameFr: 'Lesotho', nameCommon: 'Lesotho' },
  { cca2: 'LV', cca3: 'LVA', nameFr: 'Lettonie', nameCommon: 'Latvia' },
  { cca2: 'LB', cca3: 'LBN', nameFr: 'Liban', nameCommon: 'Lebanon' },
  { cca2: 'LR', cca3: 'LBR', nameFr: 'Liberia', nameCommon: 'Liberia' },
  { cca2: 'LY', cca3: 'LBY', nameFr: 'Libye', nameCommon: 'Libya' },
  { cca2: 'LI', cca3: 'LIE', nameFr: 'Liechtenstein', nameCommon: 'Liechtenstein' },
  { cca2: 'LT', cca3: 'LTU', nameFr: 'Lituanie', nameCommon: 'Lithuania' },
  { cca2: 'LU', cca3: 'LUX', nameFr: 'Luxembourg', nameCommon: 'Luxembourg' },
  { cca2: 'MO', cca3: 'MAC', nameFr: 'Macao', nameCommon: 'Macau' },
  { cca2: 'MK', cca3: 'MKD', nameFr: 'Macédoine du Nord', nameCommon: 'North Macedonia' },
  { cca2: 'MG', cca3: 'MDG', nameFr: 'Madagascar', nameCommon: 'Madagascar' },
  { cca2: 'MY', cca3: 'MYS', nameFr: 'Malaisie', nameCommon: 'Malaysia' },
  { cca2: 'MW', cca3: 'MWI', nameFr: 'Malawi', nameCommon: 'Malawi' },
  { cca2: 'MV', cca3: 'MDV', nameFr: 'Maldives', nameCommon: 'Maldives' },
  { cca2: 'ML', cca3: 'MLI', nameFr: 'Mali', nameCommon: 'Mali' },
  { cca2: 'MT', cca3: 'MLT', nameFr: 'Malte', nameCommon: 'Malta' },
  { cca2: 'MA', cca3: 'MAR', nameFr: 'Maroc', nameCommon: 'Morocco' },
  { cca2: 'MQ', cca3: 'MTQ', nameFr: 'Martinique', nameCommon: 'Martinique' },
  { cca2: 'MR', cca3: 'MRT', nameFr: 'Mauritanie', nameCommon: 'Mauritania' },
  { cca2: 'YT', cca3: 'MYT', nameFr: 'Mayotte', nameCommon: 'Mayotte' },
  { cca2: 'MX', cca3: 'MEX', nameFr: 'Mexique', nameCommon: 'Mexico' },
  { cca2: 'FM', cca3: 'FSM', nameFr: 'Micronésie', nameCommon: 'Micronesia' },
  { cca2: 'MD', cca3: 'MDA', nameFr: 'Moldavie', nameCommon: 'Moldova' },
  { cca2: 'MC', cca3: 'MCO', nameFr: 'Monaco', nameCommon: 'Monaco' },
  { cca2: 'MN', cca3: 'MNG', nameFr: 'Mongolie', nameCommon: 'Mongolia' },
  { cca2: 'ME', cca3: 'MNE', nameFr: 'Monténégro', nameCommon: 'Montenegro' },
  { cca2: 'MS', cca3: 'MSR', nameFr: 'Montserrat', nameCommon: 'Montserrat' },
  { cca2: 'MZ', cca3: 'MOZ', nameFr: 'Mozambique', nameCommon: 'Mozambique' },
  { cca2: 'NA', cca3: 'NAM', nameFr: 'Namibie', nameCommon: 'Namibia' },
  { cca2: 'NR', cca3: 'NRU', nameFr: 'Nauru', nameCommon: 'Nauru' },
  { cca2: 'NP', cca3: 'NPL', nameFr: 'Népal', nameCommon: 'Nepal' },
  { cca2: 'NI', cca3: 'NIC', nameFr: 'Nicaragua', nameCommon: 'Nicaragua' },
  { cca2: 'NE', cca3: 'NER', nameFr: 'Niger', nameCommon: 'Niger' },
  { cca2: 'NG', cca3: 'NGA', nameFr: 'Nigéria', nameCommon: 'Nigeria' },
  { cca2: 'NU', cca3: 'NIU', nameFr: 'Niue', nameCommon: 'Niue' },
  { cca2: 'NO', cca3: 'NOR', nameFr: 'Norvège', nameCommon: 'Norway' },
  { cca2: 'NC', cca3: 'NCL', nameFr: 'Nouvelle-Calédonie', nameCommon: 'New Caledonia' },
  { cca2: 'NZ', cca3: 'NZL', nameFr: 'Nouvelle-Zélande', nameCommon: 'New Zealand' },
  { cca2: 'OM', cca3: 'OMN', nameFr: 'Oman', nameCommon: 'Oman' },
  { cca2: 'UG', cca3: 'UGA', nameFr: 'Ouganda', nameCommon: 'Uganda' },
  { cca2: 'UZ', cca3: 'UZB', nameFr: 'Ouzbékistan', nameCommon: 'Uzbekistan' },
  { cca2: 'PK', cca3: 'PAK', nameFr: 'Pakistan', nameCommon: 'Pakistan' },
  { cca2: 'PW', cca3: 'PLW', nameFr: 'Palaos (Palau)', nameCommon: 'Palau' },
  { cca2: 'PS', cca3: 'PSE', nameFr: 'Palestine', nameCommon: 'Palestine' },
  { cca2: 'PA', cca3: 'PAN', nameFr: 'Panama', nameCommon: 'Panama' },
  { cca2: 'PG', cca3: 'PNG', nameFr: 'Papouasie-Nouvelle-Guinée', nameCommon: 'Papua New Guinea' },
  { cca2: 'PY', cca3: 'PRY', nameFr: 'Paraguay', nameCommon: 'Paraguay' },
  { cca2: 'NL', cca3: 'NLD', nameFr: 'Pays-Bas', nameCommon: 'Netherlands' },
  { cca2: 'BQ', cca3: 'BES', nameFr: 'Pays-Bas caribéens', nameCommon: 'Caribbean Netherlands' },
  { cca2: 'PE', cca3: 'PER', nameFr: 'Pérou', nameCommon: 'Peru' },
  { cca2: 'PH', cca3: 'PHL', nameFr: 'Philippines', nameCommon: 'Philippines' },
  { cca2: 'PL', cca3: 'POL', nameFr: 'Pologne', nameCommon: 'Poland' },
  { cca2: 'PF', cca3: 'PYF', nameFr: 'Polynésie française', nameCommon: 'French Polynesia' },
  { cca2: 'PR', cca3: 'PRI', nameFr: 'Porto Rico', nameCommon: 'Puerto Rico' },
  { cca2: 'PT', cca3: 'PRT', nameFr: 'Portugal', nameCommon: 'Portugal' },
  { cca2: 'QA', cca3: 'QAT', nameFr: 'Qatar', nameCommon: 'Qatar' },
  { cca2: 'CF', cca3: 'CAF', nameFr: 'République centrafricaine', nameCommon: 'Central African Republic' },
  { cca2: 'DO', cca3: 'DOM', nameFr: 'République dominicaine', nameCommon: 'Dominican Republic' },
  { cca2: 'RE', cca3: 'REU', nameFr: 'Réunion', nameCommon: 'Réunion' },
  { cca2: 'RO', cca3: 'ROU', nameFr: 'Roumanie', nameCommon: 'Romania' },
  { cca2: 'GB', cca3: 'GBR', nameFr: 'Royaume-Uni', nameCommon: 'United Kingdom' },
  { cca2: 'RU', cca3: 'RUS', nameFr: 'Russie', nameCommon: 'Russia' },
  { cca2: 'RW', cca3: 'RWA', nameFr: 'Rwanda', nameCommon: 'Rwanda' },
  { cca2: 'EH', cca3: 'ESH', nameFr: 'Sahara Occidental', nameCommon: 'Western Sahara' },
  { cca2: 'BL', cca3: 'BLM', nameFr: 'Saint-Barthélemy', nameCommon: 'Saint Barthélemy' },
  { cca2: 'KN', cca3: 'KNA', nameFr: 'Saint-Christophe-et-Niévès', nameCommon: 'Saint Kitts and Nevis' },
  { cca2: 'SM', cca3: 'SMR', nameFr: 'Saint-Marin', nameCommon: 'San Marino' },
  { cca2: 'MF', cca3: 'MAF', nameFr: 'Saint-Martin', nameCommon: 'Saint Martin' },
  { cca2: 'SX', cca3: 'SXM', nameFr: 'Saint-Martin', nameCommon: 'Sint Maarten' },
  { cca2: 'PM', cca3: 'SPM', nameFr: 'Saint-Pierre-et-Miquelon', nameCommon: 'Saint Pierre and Miquelon' },
  { cca2: 'VC', cca3: 'VCT', nameFr: 'Saint-Vincent-et-les-Grenadines', nameCommon: 'Saint Vincent and the Grenadines' },
  { cca2: 'SH', cca3: 'SHN', nameFr: 'Sainte-Hélène, Ascension et Tristan da Cunha', nameCommon: 'Saint Helena, Ascension and Tristan da Cunha' },
  { cca2: 'LC', cca3: 'LCA', nameFr: 'Sainte-Lucie', nameCommon: 'Saint Lucia' },
  { cca2: 'SV', cca3: 'SLV', nameFr: 'Salvador', nameCommon: 'El Salvador' },
  { cca2: 'WS', cca3: 'WSM', nameFr: 'Samoa', nameCommon: 'Samoa' },
  { cca2: 'AS', cca3: 'ASM', nameFr: 'Samoa américaines', nameCommon: 'American Samoa' },
  { cca2: 'ST', cca3: 'STP', nameFr: 'São Tomé et Príncipe', nameCommon: 'São Tomé and Príncipe' },
  { cca2: 'SN', cca3: 'SEN', nameFr: 'Sénégal', nameCommon: 'Senegal' },
  { cca2: 'RS', cca3: 'SRB', nameFr: 'Serbie', nameCommon: 'Serbia' },
  { cca2: 'SC', cca3: 'SYC', nameFr: 'Seychelles', nameCommon: 'Seychelles' },
  { cca2: 'SL', cca3: 'SLE', nameFr: 'Sierra Leone', nameCommon: 'Sierra Leone' },
  { cca2: 'SG', cca3: 'SGP', nameFr: 'Singapour', nameCommon: 'Singapore' },
  { cca2: 'SK', cca3: 'SVK', nameFr: 'Slovaquie', nameCommon: 'Slovakia' },
  { cca2: 'SI', cca3: 'SVN', nameFr: 'Slovénie', nameCommon: 'Slovenia' },
  { cca2: 'SO', cca3: 'SOM', nameFr: 'Somalie', nameCommon: 'Somalia' },
  { cca2: 'SD', cca3: 'SDN', nameFr: 'Soudan', nameCommon: 'Sudan' },
  { cca2: 'SS', cca3: 'SSD', nameFr: 'Soudan du Sud', nameCommon: 'South Sudan' },
  { cca2: 'LK', cca3: 'LKA', nameFr: 'Sri Lanka', nameCommon: 'Sri Lanka' },
  { cca2: 'SE', cca3: 'SWE', nameFr: 'Suède', nameCommon: 'Sweden' },
  { cca2: 'CH', cca3: 'CHE', nameFr: 'Suisse', nameCommon: 'Switzerland' },
  { cca2: 'SR', cca3: 'SUR', nameFr: 'Surinam', nameCommon: 'Suriname' },
  { cca2: 'SJ', cca3: 'SJM', nameFr: 'Svalbard et Jan Mayen', nameCommon: 'Svalbard and Jan Mayen' },
  { cca2: 'SY', cca3: 'SYR', nameFr: 'Syrie', nameCommon: 'Syria' },
  { cca2: 'TJ', cca3: 'TJK', nameFr: 'Tadjikistan', nameCommon: 'Tajikistan' },
  { cca2: 'TW', cca3: 'TWN', nameFr: 'Taïwan', nameCommon: 'Taiwan' },
  { cca2: 'TZ', cca3: 'TZA', nameFr: 'Tanzanie', nameCommon: 'Tanzania' },
  { cca2: 'TD', cca3: 'TCD', nameFr: 'Tchad', nameCommon: 'Chad' },
  { cca2: 'CZ', cca3: 'CZE', nameFr: 'Tchéquie', nameCommon: 'Czechia' },
  { cca2: 'TF', cca3: 'ATF', nameFr: 'Terres australes et antarctiques françaises', nameCommon: 'French Southern and Antarctic Lands' },
  { cca2: 'IO', cca3: 'IOT', nameFr: 'Territoire britannique de l\'océan Indien', nameCommon: 'British Indian Ocean Territory' },
  { cca2: 'TH', cca3: 'THA', nameFr: 'Thaïlande', nameCommon: 'Thailand' },
  { cca2: 'TL', cca3: 'TLS', nameFr: 'Timor oriental', nameCommon: 'Timor-Leste' },
  { cca2: 'TG', cca3: 'TGO', nameFr: 'Togo', nameCommon: 'Togo' },
  { cca2: 'TK', cca3: 'TKL', nameFr: 'Tokelau', nameCommon: 'Tokelau' },
  { cca2: 'TO', cca3: 'TON', nameFr: 'Tonga', nameCommon: 'Tonga' },
  { cca2: 'TT', cca3: 'TTO', nameFr: 'Trinité-et-Tobago', nameCommon: 'Trinidad and Tobago' },
  { cca2: 'TN', cca3: 'TUN', nameFr: 'Tunisie', nameCommon: 'Tunisia' },
  { cca2: 'TM', cca3: 'TKM', nameFr: 'Turkménistan', nameCommon: 'Turkmenistan' },
  { cca2: 'TR', cca3: 'TUR', nameFr: 'Turquie', nameCommon: 'Türkiye' },
  { cca2: 'TV', cca3: 'TUV', nameFr: 'Tuvalu', nameCommon: 'Tuvalu' },
  { cca2: 'UA', cca3: 'UKR', nameFr: 'Ukraine', nameCommon: 'Ukraine' },
  { cca2: 'UY', cca3: 'URY', nameFr: 'Uruguay', nameCommon: 'Uruguay' },
  { cca2: 'VU', cca3: 'VUT', nameFr: 'Vanuatu', nameCommon: 'Vanuatu' },
  { cca2: 'VE', cca3: 'VEN', nameFr: 'Venezuela', nameCommon: 'Venezuela' },
  { cca2: 'VN', cca3: 'VNM', nameFr: 'Viêt Nam', nameCommon: 'Vietnam' },
  { cca2: 'WF', cca3: 'WLF', nameFr: 'Wallis-et-Futuna', nameCommon: 'Wallis and Futuna' },
  { cca2: 'YE', cca3: 'YEM', nameFr: 'Yémen', nameCommon: 'Yemen' },
  { cca2: 'ZM', cca3: 'ZMB', nameFr: 'Zambie', nameCommon: 'Zambia' },
  { cca2: 'ZW', cca3: 'ZWE', nameFr: 'Zimbabwe', nameCommon: 'Zimbabwe' },
];
