export default interface CahierConge{
    empmat:string,
    emplib:string,
    empdnais:Date,
    empemb:Date,
    empreg:string,
    saljou:number,
    somper:number,
    pretemps:string,
    soldini:number,
    congedu:number,
    indemdu:number,
    jouanc:number,
    montanc:number,
    conjeutrv:number,
    montjeutrv:number,
    jourjeutrv:number,
    montjourjeutrv:number,
    totdupres:number,
    indemcong:number,
    datdep:number,
    depam:number,
    datret:number,
    retam:number,

}