export type Filiale = {
    sitcod: string,
    soccod: string,
    sitlib: string,
    sitadr: string,
    sittel: string,
    sitfax: string,
    sitemail: string,
    sitmois: number,
    sitconge: number,
    sitcongem: number,
    sitsoc: string,
    sitpaie: string,
    sitsanch: string,
    sitsancm: string,
    // Geofence : si renseignés, le pointage exige une position GPS dans le rayon défini.
    sitlat?: number | null,
    sitlon?: number | null,
    sitrad?: number | null,
};